### ISSUE TITLE
Back button does unexpected behavior

### ISSUE THREAD

**Issue by abou123** [falzonv/discreet-launcher#1]
When I press the back button in the app drawer, favorites manager, about screen, or menu, it takes me back to the home screen (which is what I would expect); but when I press the back button on the home screen or the favorites, it takes me to a black screen that doesn't do anything

**Comment by falzonv** [comment]
Hello,

Thank you very much for your feedback and tests.
I was able to resolve the issue in release v1.0.2 which has been pushed to GitHub few minutes ago.

Now pressing the Back button of the home screen will hide the favorites panel.
If this panel was already hidden, pressing the button will do nothing (as we want to stay on the home screen).

This will probably take a couple of days to be fully replicated in the F-Droid repository.
Once it is there, could you please upgrade the application to confirm it solved the issue for you?

Best regards.

**Comment by abou123** [comment]
Awesome!  Thank you very much!  

Stay safe!

**Comment by falzonv** [comment]
Hello,

For information, release v1.0.2 is now available on F-Droid since yesterday 11th March (so it took 4 days from the GitHub push to availability in the repository).
Since it is resolved, I will close the issue but feel free to add comments if needed.

Best regards.
