### ISSUE TITLE
Remove favorites limit

### ISSUE THREAD

**Issue by falzonv** [falzonv/discreet-launcher#100]
This ticket is created following a suggestion from @xi7 in ticket #99:

> limit while only icons favorites can be increase.

---

Yes maybe, in fact I am now thinking that perhaps this limit could even be completely removed.

It was added to solve #19 because, at the time, the only way to access the favorites selector was to use the menu button (so the only way to see the menu button again was to remove favorites... using the unreachable menu button!).

Since #59 the menu is also accessible from the launcher icon in the app drawer so there is not much issue if the menu button is not visible anymore due to too many favorites (as it can even be hidden in the settings).

I will have a look and keep you updated ;-)

**Comment by xi7** [comment]
![Screenshot_2021-08-04-06-55-03](https://user-images.githubusercontent.com/67331785/128163305-b459efb6-0a94-4838-8ad1-5a66ef27ccb6.png)

possible add next update the option reverse interface with reverse fill icons ?

-current load icons same the drawer
-use it with reverse fill too

**Comment by xi7** [comment]
and when active **no app drawer** with **no menu button** need reinstall the app because not possible use settings or when new app intalled cant use it.

**Comment by falzonv** [comment]
> possible add next update the option reverse interface with reverse fill icons ?

=> Maybe, but this is not something I plan to implement for now.
I guess the reason for this request is because currently you can set only 12 favorites?
With the next release, this limit will be removed so you could have 14 favorites => 2 complete rows with no holes.

---

> and when active **no app drawer** with **no menu button** need reinstall the app because not possible use settings

=> You can use the Search to click the launcher icon and access the menu.
*Note: if the menu button is hidden and the user doesn't have the launcher or Search icon in its favorites, the "no app drawer" option will be automatically disabled.*

> or when new app intalled cant use it.

=> When disabling the app drawer, you will need to use the Search (= all apps) to access a new application (you can also add the new app to the favorites from the menu).

**Comment by xi7** [comment]
> > possible add next update the option reverse interface with reverse fill icons ?
> 
> => Maybe, but this is not something I plan to implement for now.
> I guess the reason for this request is because currently you can set only 12 favorites?
> With the next release, this limit will be removed so you could have 14 favorites => 2 complete rows with no holes.

but it will always have holes after add new item alignment, up to down is better visualization

**Comment by falzonv** [comment]
I made some tries to reverse the order but the only option that works (setting a "reverse_layout" parameter to "true") doesn't look good because it only reverse the lines (see screenshot 3).
Since it would mess with people custom favorites order, I will not implement this.

| Initial setup | Current (for comparison) | With "reverse_layout" = true |
| --- | --- | --- |
| ![2021-08-15_reverse_fill_order1](https://user-images.githubusercontent.com/4698531/129471918-9aebd54c-b80b-42e8-9a99-e4dc4875d216.jpg) | ![2021-08-15_reverse_fill_order2](https://user-images.githubusercontent.com/4698531/129471920-04203cf4-8f3a-48bf-92d3-980a767bd6fc.jpg) | ![2021-08-15_reverse_fill_order3](https://user-images.githubusercontent.com/4698531/129471921-6eea10dc-2789-42b7-b7a8-e99e5fe348f4.jpg)

**Comment by xi7** [comment]
pic 3 is very good and not mess favorires, This is the correct how to show.

**Comment by falzonv** [comment]
It does mess favorites when comparing the on-screen display to the list in the interface allowing to sort favorites.

| Order on screen | Order in the list |
| --- | --- |
| Browser | Calculator |
| Settings | Firefox |
| Startpage | Clock |
| (blank) | Gallery |
| Calculator | Browser |
| Firefox | Settings |
| Clock | Startpage |
| Gallery |  |

If I implemented this, I am sure few days after I would get tickets (maybe even from you) saying that the sort favorites feature has become unusable in reverse interface mode.
Even when there is no hole, it would still mix the lines between the real order and the reality, for example:


| Order on screen | Order in the list |
| --- | --- |
| Browser | Calculator |
| Settings | Firefox |
| Startpage | Clock |
| Search | Gallery |
| Calculator | Browser |
| Firefox | Settings |
| Clock | Startpage |
| Gallery | Search |

It would solve a display bug in some cases, but make the sorting feature much less user-friendly to use.
Sorry, as I said this will not be implemented.

**Comment by falzonv** [comment]
Hello,

I am pleased to inform you that the favorites limit has been removed in new release v4.7.0!
This release has been published few minutes ago.

Here are the usual availability delays for each location:
- 4 to 8 days on F-Droid
- 0 to 2 days on Google Play
- Already available as direct APK on GitHub (https://github.com/falzonv/discreet-launcher/releases)

*Remarks:
I will leave this ticket opened until the release is effectively published on F-Droid.
You can use the export/import feature to switch from one version to another.*

Best regards.

**Comment by xi7** [comment]
https://user-images.githubusercontent.com/67331785/129550971-3caa6fb2-abe8-4885-9be2-88aded33bfa6.mp4
**the video show gridview and favorites , reverse mode on/off**


you understand the method implemented with or without mode reverse if you add all grid list to favorites list will be same effect and the effect reverse will be useless ?

**Comment by falzonv** [comment]
I must admit it took me a second watch to understand the video, it looks funny, like 2 app drawers :joy:

More seriously, it is now possible to put all apps in the favorites but this is not the way the launcher is intended to work.
If you put all apps in the favorites, it will indeed make some features/options redundant, but I will not remove them from the launcher because they are still valid in a normal use.

**Comment by xi7** [comment]
will work with minimum code using list a-z and z-a organization

**Comment by falzonv** [comment]
To make it more explicit, I consider the use case of having all apps in favorites as out of scope (because it defeats the concept of "favorites") and I will not work on features specific to this use case.

Even in reverse mode, showing the app drawer in Z-A order would be confusing for most users and will not be done.
You can, if you have the patience, order the favorites manually in Z-A order but I do not plan to add a feature doing this automatically as there shouldn't be so much favorites in a normal use.

*Remark: I will be away from Internet and GitHub for a couple of weeks.*

**Comment by xi7** [comment]
what about 

- no icons (show only label) / save memory no cache needed.

**Comment by falzonv** [comment]
Hello,

"what about no icons (show only label) / save memory no cache needed."

After giving it a try, only labels looks mostly confusing and unreadable in grid view.
It could look better if changing to list view, but this would almost be like implementing a new launcher so I will not do that.

*Remark: since v4.7.0 is available on F-Droid, I will close this ticket.*

**Comment by xi7** [comment]
possible u make a (service activity search) by gesture, like windows when press win key+E show explorer, this case show ``search`` while out home.

it will be better than notification bar and faster search all scene and delete all notification also icon search house.

**Comment by falzonv** [comment]
No, this is not possible. The closest way would be a Search from notification but we already saw in another ticket that it doesn't work well for technical reasons (it slows down the launcher a lot).

**Comment by xi7** [comment]
all system android can be configure smart button, smart motion, system gestures.
example: 3 finger screeshot, C gesture start config, answer by swing...

**are you really sure that nothing can call favorites with all these solutions ?**

any 2 finger will be great and better than slide notification by click.

**Comment by xi7** [comment]
benchmark out home:

press home + slide up/down = show favorites (2 command) **normal**
slide notification + click = show favorites (2 command) **slow** 
two finger = show favotires = (1 command) **fastest**

**Comment by xi7** [comment]
https://user-images.githubusercontent.com/67331785/133849857-ef905ce9-f94e-4f39-853c-24ef013fcc70.mp4

what about u use this friendly design

**Comment by falzonv** [comment]
Hello,

Assigning actions to gestures is possible within your own app but this is not allowed over other apps.
Otherwise, any malware app could stay in the background and steal the scrolling gesture (for example) to display ads when you scroll in your messages or in the Android settings.

Perhaps there are ways to circumvent these Android securities (otherwise malwares would not exist), but I am not interested to work on these kinds of hacks or to integrate them in my launcher.

---

Since 6 months that we are exchanging, I have the feeling that you are very unsatisfied with Discreet Launcher. You always want to have the main parts removed or completely changed as if creating a new launcher.

I created Discreet Launcher in 2019 and use it on my own phone since then. In 2021, I thought that this small launcher may interest other people so I decided to publish it on F-Droid and Google Play.
Personally, even if all the features added since v1.0.0 disappeared, I would still be very happy with this launcher.

If you are not satisfied with the concepts of Discreet Launcher (no worries, I won't be vexed), please try other launchers.
There are [dozens of them on F-Droid](https://search.f-droid.org/?q=launcher) (and [literally hundreds on Google Play](https://play.google.com/store/search?q=launcher&c=apps)) and some have very different and interesting concepts and features (such as [Pie Launcher](https://f-droid.org/packages/de.markusfisch.android.pielauncher/) or [Luke Launcher](https://f-droid.org/packages/luke.launcher/) to give F-Droid examples).

Best regards.

**Comment by xi7** [comment]
![Screenshot_2021-09-18-06-30-30](https://user-images.githubusercontent.com/67331785/133885416-4f6e9594-0a93-496b-8b35-cbcb1dc6dde9.png)

the actual solution cant restore original name after rename, if u like implement with the shadow, like this.

**Comment by xi7** [comment]
![Screenshot_2021-09-18-07-20-47](https://user-images.githubusercontent.com/67331785/133885576-66971894-2239-4dbd-800c-20321d6aba0c.png)

not possible remove this white target while locked phone ?

**Comment by falzonv** [comment]
Ok, restore the original name if the new name is empty (+ shadow showing original name) will be implemented in next release.

The weird white target is probably not related to Discreet Launcher because the notification is already set as [VISIBILITY_SECRET](https://developer.android.com/reference/android/app/Notification.html#VISIBILITY_SECRET) which is the most hidden, also it has a "Favorites" text in it while yours is empty.

**Comment by xi7** [comment]
https://user-images.githubusercontent.com/67331785/134155692-33c6370f-9265-4d5f-ad70-80f6d38faac7.mp4

check the target lockscreeen

**Comment by xi7** [comment]
![Screenshot_2021-09-22-06-57-42](https://user-images.githubusercontent.com/67331785/134323682-c24e90d6-a576-4788-8f17-dcee57c53aa6.png)

widescreen layout menu background color no show all option

**Comment by falzonv** [comment]
> widescreen layout menu background color no show all option

Ok, fixed in next release.

---

After further tests on the notification, I now understand what happens but will not be able to solve it :-/

There are three modes proposed by Android (extract from the docs):
> - **VISIBILITY_PUBLIC**: Show this notification in its entirety on **all lockscreens**.
> - **VISIBILITY_PRIVATE**: Show this notification on **all lockscreens**, but conceal sensitive or private information on **secure lockscreens**.
> - **VISIBILITY_SECRET**: Do not reveal any part of this notification on a **secure lockscreen**.

Android makes a difference between a "simple" lockscreen (ex: swipe to unlock) and a "secure" lockscreen (ex: code, schema).

Unfortunately, there is now way to hide the notification on a "simple" lockscreen, it is possible only with a "secure" lockscreen.
