### ISSUE TITLE
Add Clock customizations

### ISSUE THREAD

**Issue by n-ce** [falzonv/discreet-launcher#103]
# Position
- Top (current default)
- Center
- Bottom
# Font
- Italic
- Condensed
- other fonts available on phone

I believe these won't be too intensive to run. Do Let me know if otherwise!

**Comment by falzonv** [comment]
Hello,

Thank you for the suggestion!

I will have a look but will make no promise to implement (all of) it because the clock is provided only for convenience, I want to keep it simple and functional to focus on the launcher features.

Best regards.

**Comment by falzonv** [comment]
Hello,

I am pleased to inform you that a setting for clock position has been added in new release v5.1.0!
This release has been published few minutes ago.

Here are the usual availability delays for each location:
- 4 to 8 days on F-Droid
- 0 to 2 days on Google Play
- Already available as direct APK on GitHub (https://github.com/falzonv/discreet-launcher/releases)

The setting related to fonts will not be feasible, but I added a setting to change the clock color instead.
(and there are also additions from tickets #84 and #114)

*Remarks:
I will leave this ticket opened until the release is effectively published on F-Droid.
You can use the export/import feature to switch from one version to another.*

Best regards.

**Comment by falzonv** [comment]
Since v5.1.0 is now available on F-Droid, I will close this ticket.
Feel free to add comments if needed or wished.
