### ISSUE TITLE
Add toggle for search icon in docker

### ISSUE THREAD

**Issue by voidskull** [falzonv/discreet-launcher#104]
I kinda updated the launcher after weeks today, and I had no issues with it, leaving out one issue.
I don't prefer that "app search" icon at the first of the docker. So I wish for the devs to have a toggle for it in the settings so I can easily turn it off.
Thanks in advance.

**Comment by xi7** [comment]
hide icon no work ?

**Comment by voidskull** [comment]
Thanks for the tip. That works now. I can now not see that search option.
Thanks again for making this launcher

**Comment by falzonv** [comment]
Hello @voidskull,

Thank you for your feedback, I am glad you like the launcher!

And thank you @xi7 to have answered faster than me ;-)
I will close this ticket but feel free to add comments if needed or wished.

Best regards.
