### ISSUE TITLE
Favorites background color not updated if "always show favorites"

### ISSUE THREAD

**Issue by tuch96** [falzonv/discreet-launcher#111]
Hi Vincent,

I have discovered an error in the "Background colour" function. If you subsequently change the coloir or transparency of the colour, this is not adopted in the favourites area.

I also have a suggestion for a further setting option here. It would be great if you could also make the favourites area transparent independently of the rest (like the function "transparent status bar").

Ciao!

![Screenshot_20210820-090234_Discreet_Launcher](https://user-images.githubusercontent.com/57192210/130194157-8f3817c3-2185-47af-b435-3269bc383cb0.png)
![Screenshot_20210820-090248_Discreet_Launcher](https://user-images.githubusercontent.com/57192210/130194183-b8faed44-c2bc-461a-9874-2a75e15eee65.png)

**Comment by falzonv** [comment]
Hello,

> If you subsequently change the coloir or transparency of the colour, this is not adopted in the favourites area.

Thank you for the report, after many tries I was finally able to reproduce the bug. It happens only when the "always show favorites" option is enabled. I guess this is because the color is updated when opening favorites, but here it never re-opens.

> I also have a suggestion for a further setting option here. It would be great if you could also make the favourites area transparent independently of the rest (like the function "transparent status bar").

Hum, maybe we should add a second color picker in this case (one for favorites area, one for drawer area).
From code perspective this looks simpler than adding a new setting which may conflict with the background color.
Would it work for you?

Best regards.

**Comment by tuch96** [comment]
> 
> Hum, maybe we should add a second color picker in this case (one for favorites area, one for drawer area).
> From code perspective this looks simpler than adding a new setting which may conflict with the background color.
> Would it work for you?
> 

Good idea. I also think that a second color picker is the simplest solution.

**Comment by falzonv** [comment]
Ok, I created ticket #120 for follow-up of the separate color pickers (as this ticket is for the bug).

**Comment by falzonv** [comment]
As a workaround waiting for the fix, I noticed that if you do a swipe like to open favorites (down in classic interface, up in reverse interface), the color is updated.

**Comment by falzonv** [comment]
Hello,

I am pleased to inform you that this has been solved in new release v5.0.0!
This release has been published few minutes ago.

Here are the usual availability delays for each location:
- 4 to 8 days on F-Droid
- 0 to 2 days on Google Play
- Already available as direct APK on GitHub (https://github.com/falzonv/discreet-launcher/releases)

*Remarks:
I will leave this ticket opened until the release is effectively published on F-Droid.
You can use the export/import feature to switch from one version to another.*

Best regards.

**Comment by tuch96** [comment]
Hi Vincent,

the 5.0.0. version runs stably and without problems on Android 10 (LineageOS). The known errors are no longer present.

Kind regards
Marc

**Comment by falzonv** [comment]
Hi Marc,

Great, thank you very much for the confirmation!

Best regards.

**Comment by tuch96** [comment]
@falzonv the f-droid version 5.0 is now out!

**Comment by falzonv** [comment]
Thank you for the notice, then I close the ticket :-)
