### ISSUE TITLE
Ability to edit/set Unsupported icons

### ISSUE THREAD

**Issue by n-ce** [falzonv/discreet-launcher#112]
- #### DESCRIPTION
There are always a few apps on our app drawers which often go missing from our icon packs and now the app collection looks odd. So it would be nice to be able to set icon of those icons.
![Screenshot_20210820-135707](https://user-images.githubusercontent.com/69345507/130204314-3bd5479e-227e-433d-aa05-79ec662ab6f5.jpg)

- #### OFF-TOPIC
Honestly as much as i'd love having it, if its app size/ memory consuming or goes beyond the scope of the app that is minimalism, I'd be happier to not have it. :)
Also, discreet is the best minimalist  launcher so far that I have used in my android experience.

**Comment by falzonv** [comment]
Hello @n-ce,

Thank you very much for the kind words, I am glad you like Discreet Launcher :-)
*(and sorry for the late answer, I was away last weeks)*

Indeed, customize app icons further than selecting a pack is out of the scope of Discreet Launcher (for history, icon packs were not even supported before v1.1.0 ; it was quite a challenge to implement).

The best way to fix missing icons is to contact the icon pack maintainer to ask for their inclusion.

Best regards.
