### ISSUE TITLE
Access settings through app settings.

### ISSUE THREAD

**Issue by Gurkenglas** [falzonv/discreet-launcher#119]
> [should always be accessible through app settings](https://github.com/falzonv/discreet-launcher/issues/117)

I'm eating my words here. I disabled the menu button and I can't find the menu anymore through app settings. Am I silly or is this a bug?
![](https://user-images.githubusercontent.com/1489801/132089145-d5742f96-1904-4f1f-ae27-ed7be9d1a8fd.png)

**Comment by falzonv** [comment]
Hello,

There are two ways to access the launcher menu:
- Using the menu button
- Using the Discreet Launcher icon (it becomes the only way when the menu button is disabled)

It was never accessible from app settings and, as far as I know, this cannot be implemented.

Best regards.
