### ISSUE TITLE
Separate color pickers for favorites and drawer areas

### ISSUE THREAD

**Issue by falzonv** [falzonv/discreet-launcher#120]
This ticket is created following discussion with @tuch96 in #111:

> > > **Marc:** I also have a suggestion for a further setting option here. It would be great if you could also make the favourites area transparent independently of the rest (like the function "transparent status bar").
> > 
> > **Vincent:** Hum, maybe we should add a second color picker in this case (one for favorites area, one for drawer area).
From code perspective this looks simpler than adding a new setting which may conflict with the background color.
Would it work for you?
> 
> **Marc:** Good idea. I also think that a second color picker is the simplest solution.

**Comment by falzonv** [comment]
Hello Marc (@tuch96),

As you saw in the translation files, this has been implemented in new release v5.2.0!
I will leave this ticket open until it is available on F-Droid (usually takes 4 to 8 days).

Best regards.

**Comment by tuch96** [comment]
Hi Vincent,

the new f-droid version is out. Especially the separate control of the background color works perfectly. A great addition. Good job!!

Best regards
Marc

**Comment by falzonv** [comment]
Perfect, thank you for the feedback!
Then I close the ticket :-)
