### ISSUE TITLE
Starting with v5.0.0, Google Play version is now free

### ISSUE THREAD

**Issue by falzonv** [falzonv/discreet-launcher#122]
Hello,

For information, I have decided to switch the Google Play version from paid app to free app starting with v5.0.0.
The goal of this ticket is to give a bit more details about this.

On Google Play, there were two versions of Discreet Launcher:
- The "standard" Discreet Launcher for a small fee (~3€), using the same code than the F-Droid version.
- A "lite" version offered for free, which was stripped-out of most of the extra features (folders, shortcuts support, notification, all the settings, etc.). They were listed in the "About", mentioning the existence of the "standard" version on both Google Play (paid app) and F-Droid (free, of course).

The idea was that, because there are so many launchers to choose from, people could get a feel using the "lite" version before deciding to purchase (or not) the complete version.

Maybe it was possible to make this profitable with some techniques like showing ads in the "lite" version, proposing a trial period, in-app purchases for micro transactions, etc. Frankly, these are not things I like to see in Android apps (especially ads), so before even starting it was clear for me that I would not do that in my app.

In six months, the total amount of my Google Play revenues adds up to 25€.
For comparison, one month of my Internet connection costs me about 30€.

I am very thankful to people who decided to buy the app and I really appreciate the support.
But at the same time, I realized that it doesn't worth the effort to maintain the "lite" version, and that making everything free would allow more people to enjoy the launcher without significant financial difference for me.

This is why I decided, starting with v5.0.0, to offer the Google Play "standard" version for free and to remove the "lite" version.

Best regards.

*Remark: since this ticket is for information, I will let it open for a couple of weeks before closing it.
Feel free to add comments if needed or wished.*

**Comment by drewski-00h** [comment]
Leaving an avenue to donate is always an option.  I know I've often donated to developers who do good work.

**Comment by falzonv** [comment]
Yes, I added a donation link on GitHub, F-Droid and my website after a user suggested it in June (not in the app itself as Google Play doesn't allow it, and I don't want to make a separate F-Droid version just for this).

By the way, you are one of the first people who bought the Google Play version at the time, so thank you again for the support!

Also, I hope the goal of this ticket won't be misunderstood.
It was to explain the reasoning for the change, not to complain about money (hopefully I have a "real" job to pay my bills!).

**Comment by tuch96** [comment]
Hi Vincent, I think the decision is good and understandable!

**Comment by xi7** [comment]
in the past was limited download due to the language on playstore, I think it will get a bigger public now but is not bad idea keep it  once super lite and the other full featured.

**Comment by falzonv** [comment]
I will close the ticket now, after almost 3 months it is probably enough for an announcement :-)
