### ISSUE TITLE
flag the new app

### ISSUE THREAD

**Issue by xi7** [falzonv/discreet-launcher#134]
![Screenshot_2021-10-04-07-54-25](https://user-images.githubusercontent.com/67331785/135839572-23eee2e0-4592-4c7e-a684-a363070b8f19.png)

**when a new app is installed, makes it easier to find in the drawer / search.**

**Comment by falzonv** [comment]
Hello,

Thank you for the suggestion but this is not something I plan to implement.
When the user installs a new app, it is assumed that (s)he knows the name of this app and can easily search it.

It would also require to track the names of the apps which were recently installed and used (to disable the flag), which I do not like from privacy point of view (currently the list is refreshed when "any" app is installed, we never store its name).

Best regards.
