### ISSUE TITLE
Swipe options

### ISSUE THREAD

**Issue by jkelly2477** [falzonv/discreet-launcher#135]
Action for swipe left or right to open an app not available on Android 10 but still available on Android 8

**Comment by bob-u** [comment]
I have Android 10 and I both swipe options work great.

**Comment by jkelly2477** [comment]
Mine aren't showing the option as of which my Android 8 does . Wonder why.

**Comment by falzonv** [comment]
Hello @jkelly2477,

Could you please confirm which version of Discreet Launcher you are using?
(Left/right swipes were added only in the latest v5.1.0.)

There is no filtering related to a specific version, all settings should be available for all versions from Android 5 to 11.

Best regards.

**Comment by jkelly2477** [comment]
Well this is very strange the other day it did not even show the options and now I check it this morning and it's giving me the options so I guess we're done thank you plus I received an update from f Droid so that might have help
