### ISSUE TITLE
pick manual icon 

### ISSUE THREAD

**Issue by xi7** [falzonv/discreet-launcher#137]
https://user-images.githubusercontent.com/67331785/135834919-26e03701-e821-4193-a7e9-8a437435f303.mp4

**-manual option would be very interesting.
-visual feedback never work when change icons.**

Note:
- Why not a backup snapshot, it would be the end of your problems. (the actual method no save icons and always gives you work)

**Comment by falzonv** [comment]
Hello,

As mentioned in ticket #112, customize app icons further than selecting a pack is out of the scope of Discreet Launcher.

The visual feedback performs a white glow on the icon and emphasize its name. Indeed in some edge cases it may not be visible, like in your example with no app names and white icons.

> Why not a backup snapshot, it would be the end of your problems. (the actual method no save icons and always gives you work)

Thank you but I don't have problems currently.
Icons are saved in memory and they are retrieved only when the app list is refreshed (not "always").

Best regards.

**Comment by xi7** [comment]
https://user-images.githubusercontent.com/67331785/135934528-688e3812-a6a8-42f9-93a3-dc6b5ffe64b6.mp4

the method always checks the icon pack app ?

**Comment by xi7** [comment]
https://user-images.githubusercontent.com/67331785/136718316-04bb6b4c-08b1-485f-90b8-98735e85f595.mp4

https://play.google.com/store/apps/details?id=com.suphi.lightlaunch  (80kb)

maybe the manual way was more interesting than the random one
