### ISSUE TITLE
Add "uninstall" to app long-press menu

### ISSUE THREAD

**Issue by drewski-00h** [falzonv/discreet-launcher#140]
An "uninstall" option added to the app pop up menu would be really handy.  It's only another click away in settings, but would save some time for frequent uninstalls.

**Comment by falzonv** [comment]
Hello :-)

Thank you for the suggestion but this is not something I will implement.

From my point of view, this kind of operations should be left to the Android system (or the app store).
It also requires an additional permission ("android.permission.REQUEST_DELETE_PACKAGES") and not all apps can be uninstalled (some can only be disabled) which could create surprising bugs.

I also do not really like the idea to have a direct "uninstall" option in this menu, would be afraid to press it inadvertently!
*(even with a confirmation menu, I would still have a tense moment before clicking "no" if it's an important app :joy:)*

Best regards.
