### ISSUE TITLE
Option to apply color filter on all app icons

### ISSUE THREAD

**Issue by falzonv** [falzonv/discreet-launcher#149]
This ticket is created following suggestion from @xi7 in ticket #142:

> > > **xi7:** possible add appearance icons with bar color ?
> > > <img src="https://user-images.githubusercontent.com/67331785/139283052-f158062b-e62e-40f9-9266-4d2ff65069bc.jpg" width="50%"/>
> >
> > **falzonv:** This will not be implemented, customize app icons further than selecting a pack is out of the scope of Discreet Launcher.
>
> **xi7:** the solution presented is better than choose icon pack, with 100% hit on the icons, while choose pack with lucky doesn't reach 30%

Ok now I see your point, indeed this can be useful.
I will have a look.

**Comment by xi7** [comment]
vire urban launcher, very nice transparente filter icons.

https://user-images.githubusercontent.com/67331785/142784041-de199c3d-17e3-4f52-b209-0fb6aaa1d91a.mp4

**Comment by falzonv** [comment]
Hello,

Indeed these effects look very nice, I am not good enough with Android drawing library to do the same.

However, after hours of work (as usual), I have just finished to implement the color filter option!
It will be included in the next release, which will probably be the last one for 2021.

Here are some examples with various settings:

<img width="40%" src="https://user-images.githubusercontent.com/4698531/145680693-23120e42-d735-475f-84f5-b039b2c988be.jpg"/> <img width="40%" src="https://user-images.githubusercontent.com/4698531/145680694-a6289bce-3887-453b-a13e-b601e4e4a7b6.jpg"/> <img width="40%" src="https://user-images.githubusercontent.com/4698531/145680695-e17a58f4-040f-4acf-8d4e-15379d1586cd.jpg"/> <img width="40%" src="https://user-images.githubusercontent.com/4698531/145680697-b3adbd84-bb88-4e04-9430-0e9b925eb655.jpg"/> <img width="40%" src="https://user-images.githubusercontent.com/4698531/145680698-2e4348cf-0341-4c80-9fb9-82dcd0ddb57a.jpg"/>


Best regards.

**Comment by falzonv** [comment]
Hello,

As announced, this has been implemented in new release v5.4.0!
I will leave this ticket open until it is available on F-Droid (usually takes 4 to 8 days).

Best regards.

**Comment by falzonv** [comment]
Since yesterday v5.4.0 is now available on F-Droid so I will close this ticket.
Feel free to add comments if needed or wished.
