### ISSUE TITLE
accents sur les recherches

### ISSUE THREAD

**Issue by yukulele** [falzonv/discreet-launcher#156]
La recherche est un peu trop strict avec les accents.

Par exemple si je cherche `tel` je ne trouve pas l'application `Téléphone`, je dois taper `tél`

**Comment by falzonv** [comment]
Bonjour,

En effet, je ne l'avais pas remarqué.
Merci pour le signalement, je vais regarder comment améliorer çà ;-)

Cordialement.

*PS : je crois que c'est le premier ticket que je reçois en français sur GitHub !*

**Comment by falzonv** [comment]
Bonjour,

Cela a été modifié dans la version v5.3.0 !
Je vais laisser ce ticket ouvert jusqu'à ce qu'elle soit disponible sur F-Droid (généralement 4 à 5 jours).

Cordialement.

**Comment by yukulele** [comment]
top ! merci !

**Comment by falzonv** [comment]
Avec plaisir !
(La v5.3.0 est maintenant disponible sur F-Droid donc je ferme le ticket.)
