### ISSUE TITLE
drag/drop favorites

### ISSUE THREAD

**Issue by xi7** [falzonv/discreet-launcher#158]
drag/drop solution faster and better than open list favorites and change position order if u replace.

**Comment by falzonv** [comment]
Hello,

Perhaps, but to quite myself from another ticket (#118):
> I know several launchers do this with a long-click and icon drag-and-drop, but in this case the long-click is already assigned to other functions and the icon drag-and-drop stuff would add a lot of unnecessary complexity anyway.

> For the favorites order, I tried a couple of alternatives but will finally stay with the current implementation (it allows to avoid a lot of code complexity and maintenance troubles).

So drag and drop is not something that I plan to implement.

Best regards.
