### ISSUE TITLE
[feature request] shortcuts to shut down/reboot the smartphone

### ISSUE THREAD

**Issue by gbdomubpkm** [falzonv/discreet-launcher#161]
Hello.

This app is getting more and more amazing, thank you for your great great work.  It is my favourite launcher on a daily basis.

Is it possible to have the possibility to include these two "shortcuts" in the launcher ?

- one to shut down the smartphone ;
- the other to reboot the smartphone.

These two shortcuts would be very useful to save the use of the stop/restart side switch. Personally, I think it's a weak point of android to always have to use an off side switch to turn off or restart the smartphone and i don't like that. I haven't found currently the way (is there ?) to shut down or reboot the smartphone without using this dedicated side switch (i am on an Androïd 10 basis).

Best regards

**Comment by falzonv** [comment]
Hello,

Thank you for the kind words, I am glad you like the launcher!

Unfortunately it is not possible to have direct shutdown or reboot shortcuts in Android applications.
I guess this is to prevent malware apps to perform an auto-shutdown/reboot on app startup (if the app makes sure to be started when the phone starts, it could even make a "shutdown/reboot loop", virtually bricking the phone).

I also searched for a way to display the reboot/shutdown dialog which is displayed when pressing the button. Surprisingly, this also doesn't seem to be possible from an Android app.

Sorry, I will not be able to implement this.

Best regards.

**Comment by gbdomubpkm** [comment]
Hello.
I found and use two apps that work very well for me (android 10 AOSP).
- Power Menu (Vishnu NK) on Aurora Store for displaying reboot/shutdown dialog.
- Lock it: Sceen Off (mayank). ... Yes i didn't ask you if you can implement that 😉

Maybe it can bring you ideas 😉

**Comment by falzonv** [comment]
Hello,

Thank you for the suggestions, and by the way I am glad you already have alternatives :-)

---

Very interesting, I didn't know that Accessibility services could be used to show the reboot/shutdown dialog.

Power Menu looks great but if I want to do the same it would be like developing a brand new app and pack it in Discreet Launcher.
To be honest this is not something I will have the time to manage, and I am not very interested to reinvent the wheel knowing that a better app already exists for this ;-)

---

For screen locking, my previous findings (#48) were that it requires a special admin permission.
The Android manifest of Lock It and its first screenshot seem to confirm that:

```
<receiver android:name="com.mayank.lockit.MyAdmin" android:permission="android.permission.BIND_DEVICE_ADMIN">
   <meta-data android:name="android.app.device_admin" android:resource="@xml/policies"/>
   <intent-filter>
      <action android:name="android.app.action.DEVICE_ADMIN_ENABLED"/>
   </intent-filter>
</receiver>
```

For Discreet Launcher, I really prefer to limit permissions to what is strictly mandatory.
Currently, the only permission requested by Discreet Launcher is QUERY_ALL_PACKAGES (for obvious reasons).

Best regards.
