### ISSUE TITLE
Discreet Launcher Settings gone

### ISSUE THREAD

**Issue by aknight2015** [falzonv/discreet-launcher#170]
I accidentally hid the settings wrench from Discreet Launcher. How do I get it back?

**Comment by falzonv** [comment]
Hello,

You can also access the Discreet Launcher menu by clicking the launcher icon in the app drawer (while in Discreet Launcher, this icon becomes a shortcut to the menu).

The access via the settings wrench can be hidden, but not the access via the launcher icon. This is to always keep an access to the menu.

Best regards.
