### ISSUE TITLE
Feature idea - make the folder icons into icons 

### ISSUE THREAD

**Issue by DougGGlaass** [falzonv/discreet-launcher#171]
J'aurais préféré ne pas donner des titres et pouvoir reconnaître ce qui est dans le fichier selon l'icône...a part ça c'est vraiment top

Merci!

**Comment by falzonv** [comment]
Bonjour,

Merci pour votre retour et proposition !
Je suis content que le lanceur vous plaise :-)

Vu que la plupart des lanceurs font çà (icônes du dossier en plus petit), c'était effectivement ma première idée mais je n'y suis pas parvenu de manière satisfaisante. En plus d'ajouter beaucoup de complexité au code, les opérations de dessin consommaient trop de ressources à mon goût. Il y avait aussi plusieurs bugs d'affichage que je n'arrivais pas à résoudre, mais j'admets ne pas être un expert de la libraire de dessin Android...

Suite à ces déconvenues, j'ai fait plus simple avec une icône dérivée de celle du lanceur.
Ensuite un utilisateur a suggéré d'ajouter dans l'icône le nombre d'applications que contient le dossier, puis un autre de pouvoir changer la couleur, et pour être franc je préfère maintenant le fonctionnement actuel à l'idée que j'avais initialement. Cela fait un style un peu différent des autres lanceurs et c'est bien d'apporter de la variété.

Je ne prévois donc pas de changer cela pour l'instant, désolé.

Cordialement.

**Comment by DougGGlaass** [comment]
Merci quand même de votre réponse bien détaillé...

~Question Everything~
With sincere feelings of gratitude and deference for all bearing the name of O’Flanahbra.
everyone's beautiful faces

-------- Original Message --------
