### ISSUE TITLE
[feature request] FORCE SHUTDOWN option in the menu of an app icon.

### ISSUE THREAD

**Issue by gbdomubpkm** [falzonv/discreet-launcher#174]
By pressing and holding an icon, I would have liked to be able to activate directly, in the menu that appears, the currently missing option 'force shutdown' of an app.
For example, I often force the shutdown of my mail client before using a VPN, option which is currently not directly accessible,  because i don't want to use my mail client with a VPN at the same time.

**Comment by falzonv** [comment]
Hello,

Thank you for the suggestion but this is not something I will implement.
From what I read in Android documentation, it would require to add the permission "KILL_BACKGROUND_PROCESSES" (which looks a bit out of place for a launcher) and, as the title says, this would only work for background processes (meaning the app itself will stay active, maybe in a buggy state if the killed background process was important).
It seems to exist a permission "FORCE_STOP_PACKAGES" but I do not find it in the official documentation, from what I read across Internet this is a system permission that cannot be used by third party apps like mine.

However, you can already rather easily access this option from the long press menu: clicking "Access its settings" will lead you to the app system settings with options like force stop, clean cache or uninstall. If you do it frequently, you may often even have it in your "Recent apps" list.

Out of curiosity, why do you want to close your mail client before using a VPN?
If this VPN cannot be trusted, maybe it is not really safe to use it...

Best regards.
