### ISSUE TITLE
float favorite

### ISSUE THREAD

**Issue by xi7** [falzonv/discreet-launcher#18]
https://user-images.githubusercontent.com/67331785/113030615-2ea11d80-9164-11eb-9cd6-c31b88a9a137.mp4

is the float favorite bar better than ur homescreen and that notification ?

what u think remove both and use only the float.

**Comment by falzonv** [comment]
Hello,

Personally I prefer the current home screen and notification.
Thank you very much for the suggestion but the floating favorites bar will not be implemented.

Best regards.
