### ISSUE TITLE
Logo idea

### ISSUE THREAD

**Issue by comradekingu** [falzonv/discreet-launcher#187]
![bilde](https://user-images.githubusercontent.com/13802408/155497921-69806197-1ab3-4e3d-8101-22acea3d326d.png)

**Comment by n-ce** [comment]
Make it thinner with lesser lines, that ought to convey the minimalism of the launcher.

**Comment by falzonv** [comment]
Hello,

Thank you for the suggestion but I like the current logo and do not plan to change it for now.

Best regards.
