### ISSUE TITLE
Folder names remain when app names are hiden

### ISSUE THREAD

**Issue by Yasen6275** [falzonv/discreet-launcher#190]
Hello,
Folder names are not hiden when app names are hiden.
I think the idea of this option is to remove text labels from app drawer.
Best regards.

**Comment by falzonv** [comment]
Hello Yasen,

Good remark!

At the beginning it was not possible to assign colors to folders (the idea was there but I was not able to do it), so the workaround we found was to keep their names displayed (some history in https://github.com/falzonv/discreet-launcher/issues/26#issuecomment-834246423 and https://github.com/falzonv/discreet-launcher/issues/35#issuecomment-835159425).
Then I learnt how to change the color of some Android resources and we now have user-defined color for folders (see https://github.com/falzonv/discreet-launcher/issues/63) so this workaround of not hiding folder names is not really needed anymore.

Seeing this screenshot in https://github.com/falzonv/discreet-launcher/issues/188#issuecomment-1053218148, I think there is now also a valid use case to keep the folder names so the best is probably to manage both separately (one setting for app names and one setting for folder names).

I will have to test it but this is what I have in mind for now:

> **Current setting:**
> "No app names" (default value = false)

> **Replace it with two settings:**
> "Show app names" (default value = true)
> "Show folder names" (default value = true)

Best regards.

**Comment by falzonv** [comment]
Hello,

I am pleased to inform you that this has been implemented in new release v6.3.0!
This release has been published few minutes ago.

Here are the usual availability delays for each location:
- 4 to 8 days on F-Droid
- 0 to 2 days on Google Play
- Already available as direct APK on GitHub (https://github.com/falzonv/discreet-launcher/releases)

Finally I just added an option "No folder names" as it had some side effects to revert "No app names" into "Show app names".

*Remarks:
I will leave this ticket opened until the release is effectively published on F-Droid.
You can use the export/import feature to switch from one version to another.*

Best regards.

**Comment by falzonv** [comment]
Hello,

Since Sunday v6.3.0 is available on F-Droid so I will close this ticket.

Best regards.

**Comment by Yasen6275** [comment]
Thanks
