### ISSUE TITLE
Just a minor tweak for a Surface Duo User

### ISSUE THREAD

**Issue by DumarcMills** [falzonv/discreet-launcher#192]
Hopefully this tweak doesn't open up other tweaks.

Off the bat, the launcher works flawlessly on Surface Duo 1. I even added a windows xp background to get a desktop look to it.

Of course, the only flaw is due to the hinge. The app isn't aware of it. Apps in the favorite and draw bleed off between the screens.

I can live with that.

The only tweak I would like however, and one I think would  e easy to implement without have to deal with hinges awareness is allow for the touch target, clickable labels to be moved to the left or right side as currently bt default it is in the center.

**Comment by falzonv** [comment]
Hello,

Thank you for the report, I never thought that some Android devices could have an hinge in the middle of the screen.

Rather than adding a new setting (which in practice is never a minor tweak), I think maybe the areas where the touch targets can be clicked could simply be extended to the whole screen width instead of only the text width currently.
Although the texts would stay in the middle, the touch targets would become clickable from either left, middle or right.

Would this work for you?

Best regards.

**Comment by DumarcMills** [comment]
That's would be perfect! The surface duo is a unique foldable as it is the only one with 2 screen rather than the common single flexible screen. 
![Screenshot_20220304-105804](https://user-images.githubusercontent.com/7507268/156723235-e976ba41-d0e6-4785-80e8-80aa2a41aa2d.png)
![Screenshot_20220304-105817](https://user-images.githubusercontent.com/7507268/156723700-cd4eb051-0fc3-4a14-9822-6b46164b80aa.png)

Even portrait mode works great on this device. 

![Screenshot_20220304-110240](https://user-images.githubusercontent.com/7507268/156723678-208d6d3d-a754-42ec-872b-0063b7cb6dcc.png)



Now if that tweak isn't challenging enough, A more complex bug with the Surface Duo is the home screen. I sense the launcher works so well on duo because it treats it as one screen. 

However, when I open an app on one screen, the launcher isn't aware of this and still has the home screen expanded rather than to adjust to the other screen as a normal single screen phone.

**Comment by falzonv** [comment]
Hello,

I am pleased to inform you that the touch target areas have been extended to screen width in new release v6.1.0!
This release has been published few minutes ago.

Here are the usual availability delays for each location:
- 4 to 8 days on F-Droid
- 0 to 2 days on Google Play
- Already available as direct APK on GitHub (https://github.com/falzonv/discreet-launcher/releases)

*Remarks:
I will leave this ticket opened until the release is effectively published on F-Droid.
You can use the export/import feature to switch from one version to another.*

---

Thank you for the screenshots and additional information!

> when I open an app on one screen, the launcher isn't aware of this and still has the home screen expanded rather than to adjust to the other screen as a normal single screen phone.

=> Unfortunately this is not something I will be able to fix. It seems Microsoft released a complete development kit specially for the Surface Duo which, I guess, would allow to handle this but it goes way beyond my knowledge to be honest.

Best regards.

**Comment by falzonv** [comment]
Since a couple of days v6.1.0 is available on F-Droid so I will close this ticket.
