### ISSUE TITLE
Swipe Gesture folders

### ISSUE THREAD

**Issue by n-ce** [falzonv/discreet-launcher#193]
Currently only apps can be opened using swipe left or right gesture. How about folders too?

**Comment by falzonv** [comment]
Hello,

Thank you for the suggestion!

When the left/right swipe gestures were implemented I also tried with folders but it made the launcher crash. I don't remember the exact reason but I was not able to solve it at the time.

I will have a look on what went wrong.
This was almost one year ago and I am more experienced with Android development now, maybe I will find a way to solve it :-)

Best regards.

**Comment by falzonv** [comment]
Hello,

Swipe to open folders are now allowed in new release v6.3.0!
I will leave this ticket open until it is available on F-Droid (usually takes 4 to 8 days).

Best regards.

**Comment by falzonv** [comment]
Hello,

Since Sunday v6.3.0 is available on F-Droid so I will close this ticket.

Best regards.
