### ISSUE TITLE
Possible issue with displaying time

### ISSUE THREAD

**Issue by bob-u** [falzonv/discreet-launcher#195]
Hi

(I don't have the latest version at the moment as I use this app in my car, hence I titled prefixed this report as 'possible')

Issue: Time at noon is displayed as 0:xx PM instead of 12:xx PM 

Android clock does display the time correctly hence I believe it's the app issue.

**Comment by bob-u** [comment]
It looks like it was corrected in v5.3.0

**Comment by falzonv** [comment]
Hello,

Thank you for the report, I confirm it was solved in commit https://github.com/falzonv/discreet-launcher/commit/a4ca4427807c1fdc001a5675c5ebec9143679022 from v5.3.0 :-)

Best regards.
