### ISSUE TITLE
Feature idea - (Option for) no borders, names or X in folder and search

### ISSUE THREAD

**Issue by comradekingu** [falzonv/discreet-launcher#197]
This is a very design first idea, but I like the wall-to-wall uninterrupted aestetic of the favourites and the app drawer.

I can click outside of the fields in both folders and the search, so that isn't a problem unless the background is fully transparent.
Should still be possible to grasp that it starts not all the way at the top, or use the Android-buttons at the bottom.

For the folders I see the name no matter what. Even with all the padding removed.
This means I don't really need it when opening a folder, on the rationale of knowing what I opened.

The search currently shows every valid sequence. If "iscre" is typed, it shows "Discreet Launcher".
I am thinking if just the first letter is allowed, and then it resets for ever new key.
Type A → All apps with a word beginning with A
Type C → All apps with a word beginning with C
This takes for granted the user knows what was typed, and can figure it out from the immediacy of the result if default,
or know that it was a user-selected option from having turned it on.

It depends a little bit how many apps people have, but people can decide to use this option or not.
If there are many apps beginning with the same letter, it gets difficult without names shown.

A very "discreet" way would be to use the first icon slot for the first typed letter, and then the second(?).
It doesn't #176 move the input field to the bottom, and it makes it complex with RTL languages.
Using the entire bottom row doesn't seem right, as it would separate the list of icons, and it is no longer A: →App1 App2

but what do you think about any of this?

**Comment by falzonv** [comment]
Hello,

> (Option for) no borders, names or X in folder and search

=> I am not really fan of creating settings for these things, but I am thinking about a possible redesign for folders that could address these points at the same time.
This is what I started to mention in #196: *"I am also thinking of a possible redesign of folders, with rounded corners, no outside borders and just a line separating the title from app names ; this line could be the same color as the icon."*

> I can click outside of the fields in both folders and the search

=> Me too, but from what I remember this part was not working on Android 5, which was the reason for the X button. I will have to test again, if this works also in Android 5 I guess the X button can indeed be removed.

> For the folders I see the name no matter what. Even with all the padding removed.

=> This could not be the case anymore following ticket #190.
In addition, the folder name can be clicked to access folder settings from any open folder which is a shortcut I want to keep.

---

For the search I am not sure yet if the approach you are proposing is really better than the current one (which is indeed to search in all app names what is being typed). Will have to think about it...

Best regards.

**Comment by comradekingu** [comment]
I think a default of no borders and no X by default with no options to add them back is better.

The search field is the actual concern because it shouldn't be an overlay, and how to sort out the UI for that is a challenge.
Android 5 is from the time that devices had physical back-buttons, and the triangle down soft-button is always available to close folders or search.

It is an interesting thought to get it so right that no alternative options are needed.

**Comment by falzonv** [comment]
Hello,

> I think a default of no borders and no X by default with no options to add them back is better.

=> Fully agree.
And a good news: after further testing in an Android 5 emulator, the X is indeed not needed anymore. *(I say "anymore" because I am quite sure it was needed at first, but over time many parts of folder implementation were improved so I guess this bug has been solved in the process and I simply never noticed it.)*

> I think reserving the bottom right icon to start the search is good.

=> You mean the bottom right icon in the favorites?
This can already be configured by adding the Search in favorites and adjusting the order (providing there are enough favorites to go up to the right of the screen). Or did I misunderstood your suggestion?

---

Thank you for the launcher suggestions, I will have a look to see how their search is done.

Best regards.

**Comment by falzonv** [comment]
An issue which appears when reusing the app drawer background color is that, if this color is too transparent, the folder text/icons and the app drawer text/icons underneath start to mix and the result become difficult to read.

Here are 3 screenshots below:
=> Screenshot 1 is just after removing the X and the borders, no further color changes => OK
=> In screenshot 2, I have set the folder background to the default app drawer background color => already not so OK
=> In screenshot 3, I have set the app drawer background to transparent, and the folder background accordingly, as if it was reusing this color (for now I just hard-coded the value for testing) => definitely not OK

<img src="https://user-images.githubusercontent.com/4698531/158266569-b196190a-1874-4bd9-a62c-f4b0774ad061.jpg" width="30%"/> <img src="https://user-images.githubusercontent.com/4698531/158266617-f882bf02-3b11-47c0-bc3e-736f56fab0b4.jpg" width="30%"/> <img src="https://user-images.githubusercontent.com/4698531/158266624-1da33338-2e45-4bea-99cb-eb55324cde36.jpg" width="30%"/>

---

Note: in a previous comment I talked about rounded corners for folders, but after further testing I will stick to normal corners.
Rounded corners add a lot of internal complexity if we want to reuse the app drawer user-defined color in a custom shape like this. It also creates glitches with the popup for favorites, and after removing the borders and comparing both I think normal corners look better than rounded anyway.

**Comment by xi7** [comment]
screenshot 1 is good, but i will like more if put centralized icons folder and fav

**Comment by falzonv** [comment]
Hello,

@xi7:
Thank you for your feedback!
Not sure if icons can be centered in this kind of Android view (called RecyclerView) but I will have a look :-)

---

@comradekingu:
I created a separate ticket (#202) to discuss the search. It is in fact a separate topic that will probably take more time than borders, X and colors (to be honest I didn't had the time yet to even start looking into it).

For the issue mentioned above about transparency, I was able to find a solution that should work in most cases.
With the default settings it would look like screenshot 1. Then if the user changes the app drawer background color, to translucent blue for example, the folder background color would use a similar tint of blue (slightly lighter to make the folder more visible) with the same level of transparency than screenshot 1 so icons/text stays distinct from the app drawer.

Also, I was thinking to maybe add a gear icon (the same than for the menu button) at top right of the folder where the X was before. This would make more explicit that clicking the title of the folder allows to access folder settings (it is already mentioned in the Help, but I am not sure many people take the time to read Helps now...).
=> What do you think of it?

Best regards.

**Comment by comradekingu** [comment]
@falzonv 
How about instead the base layer background is fully opaque once something is entered in the search?
(Option 3, only with the apps blurred instead)
If the search is also fullscreen it will look as if the search isn't actually an overlay, but rather apps are searched in situ.

For the full effect, the search background could be the user wallpaper, which means more wallpaper, less elements,
and no evidence of an overlay.

A folder could expand to be shown amongst the apps that surround it

App 1 app 2 app 3 folder 1 [+]
app 4 app 5

Becomes

App 1 app 2 app 3
------------------------
Content of folder 1 [-]
app 1 in folder 1, app 2 in folder 1
-------------------------
app 4 app 5 

I suppose this would mean other apps need to be pushed downwards the length the expanded folder content takes up.
It would give an intuitive way to move apps in and out of folders.

**Comment by falzonv** [comment]
Hello,

Thank you for the new suggestions, although these are not things I am capable to implement and maintain to be honest (blur app icons, dynamically split a grid view in two to insert another view in the middle, etc.), at least not in a resource efficient way.

---

Now I think I have finished to work on this ticket, that will bring many improvements :-)

When the next release will be published (not ready yet), the following will be changed:
- No external borders anymore, only a line between folder title and content will remain like in screenshot 1 above
- The X is replaced by a gear icon (same as the menu icon) to make more explicit that clicking the header opens settings
- Related to ticket #196:
  - The folder title and the separating line will be the same color as the folder icon
  - The folder background will be based on app drawer background color, with a transparency like in screenshot 1 above to make sure app icons and names always stay visible
  - The app names will be the same color as the text color selected for the app drawer

> > **xi7:**
> > screenshot 1 is good, but i will like more if put centralized icons folder and fav
>
> **falzonv:**
> Thank you for your feedback!
> Not sure if icons can be centered in this kind of Android view (called RecyclerView) but I will have a look :-)

=> After further testing, due to the way the grid view works, I am not able to center the icons.

Best regards.

**Comment by falzonv** [comment]
Hello,

What was described in the last comment has been implemented in v6.2.0!
I will leave this ticket open until it is available on F-Droid (usually takes 4 to 8 days).

Best regards.

**Comment by falzonv** [comment]
Since yesterday v6.2.0 is available on F-Droid so I will close this ticket.
