### ISSUE TITLE
Feature idea - Modify the search approach

### ISSUE THREAD

**Issue by falzonv** [falzonv/discreet-launcher#202]
This ticket is created following discussion with @comradekingu in ticket #197:

> > > > **comradekingu:**
> > > > The search currently shows every valid sequence. If "iscre" is typed, it shows "Discreet Launcher".
> > > > I am thinking if just the first letter is allowed, and then it resets for ever new key.
> > > > Type A → All apps with a word beginning with A
> > > > Type C → All apps with a word beginning with C
> > > > This takes for granted the user knows what was typed, and can figure it out from the immediacy of the result if default,
> > > > or know that it was a user-selected option from having turned it on.
> > > >
> > > > It depends a little bit how many apps people have, but people can decide to use this option or not.
> > > > If there are many apps beginning with the same letter, it gets difficult without names shown.
> > > > 
> > > > A very "discreet" way would be to use the first icon slot for the first typed letter, and then the second(?).
> > > > It doesn't #176 move the input field to the bottom, and it makes it complex with RTL languages.
> > > > Using the entire bottom row doesn't seem right, as it would separate the list of icons, and it is no longer A: →App1 App2
> > > > 
> > > > but what do you think about any of this?
> > > 
> > > **falzonv:**
> > > For the search I am not sure yet if the approach you are proposing is really better than the current one (which is indeed to search in all app names what is being typed). Will have to think about it...
> > 
> > **comradekingu:**
> > The search field is the actual concern because it shouldn't be an overlay, and how to sort out the UI for that is a challenge.
> >
> > It is an interesting thought to get it so right that no alternative options are needed.
> > I think reserving the bottom right icon to start the search is good.
> > Edit: OpenLauncher has something similar with a floating button that opens a fullscreen search, albeit not one that is shown by default.
> > PoseidonLauncher has a field at the bottom for clicking search, but it isn't as sleek as just the magnifying icon.
> > Text Launcher has the right setup, but it only has text, and the field is up top.
> > TinyBit launcher has an overlay, but the input field is correctly at the bottom.
> > KISS/Sentien have the most things right, but it isn't sleek.
> 
> **falzonv:**
> You mean the bottom right icon in the favorites?
> This can already be configured by adding the Search in favorites and adjusting the order (providing there are enough favorites to go up to the right of the screen). Or did I misunderstood your suggestion?
> 
> Thank you for the launcher suggestions, I will have a look to see how their search is done.

Since this is a different (and more complex) topic than the original ticket, I create this one for better follow-up.

**Comment by xi7** [comment]
i dont undestand this issue but need fix the search after show 2 or more apps press enter nothing happen, only when show 1 app press enter work.

**Comment by comradekingu** [comment]
@xi7 That isn't the issue here, and it works for me. You can open a new issue about it. :)

**Comment by xi7** [comment]
https://user-images.githubusercontent.com/67331785/160235680-eff354b6-6102-4c96-b5af-b5ee9a43c9d0.mp4

look the big search difference, i press `C` enter - `A` enter ... never show or open calculator. 
the second lancher , i just press C and calculator open easy, and D show discreet launcher and open after enter...

the discreeet launcher here need write full name or no work after press enter.

**Comment by falzonv** [comment]
Hello,

@xi7:
I confirm that when there is only 1 result remaining, pressing Enter opens it.
This is not shown in your video but it would be the case after typing "cal", there is no need to enter the full name.

---

At the very beginning of the discussion, @comradekingu made this remark:

> The search currently shows every valid sequence. If "iscre" is typed, it shows "Discreet Launcher".
> I am thinking if just the first letter is allowed, and then it resets for ever new key.
> Type A → All apps with a word beginning with A
> Type C → All apps with a word beginning with C

I don't really like the approach to allow only one letter, but the idea to show only apps "having a word starting with the searched sequence" (instead of "containing the searched sequence" currently) is interesting.
This would allow to reduce faster the number of results down to 1 that could be opened with Enter.

For example in the video:
=> Typing "c" would give only 6 results instead of at least 12 currently
=> Typing "ca" would give only 2 results (Calculator and Camera) instead of 5 currently
In addition, with the changes from https://github.com/falzonv/discreet-launcher/issues/176#issuecomment-1078047270 these fewer results would also be just above the keyboard.

Not sure how to do this yet but I will have a look...

Best regards.

**Comment by falzonv** [comment]
Actually, thinking about ...

> the idea to show only apps "having a word starting with the searched sequence" (instead of "containing the searched sequence" currently) is interesting.

... there is not much added value to try matching the beginning of *any* word in the app name.
Just checking if the app name *starts* with the searched sequence is enough.

I will implement this, it is also much more efficient than the current approach to search at every position in the app name.

Once this is implemented, and with the improvements from https://github.com/falzonv/discreet-launcher/issues/176#issuecomment-1078047270, I think this ticket will be solved :-)

**Comment by xi7** [comment]
v6.2.0 the launcher crash after write wrong name

**Comment by falzonv** [comment]
Hello,

Thank you for the report, I will have a look.

Also, did you tried to press Enter when there *are* search results?
This should launch the first app as you asked (by the way I think it was this change which introduced the bug you just noticed...).

Best regards.

**Comment by falzonv** [comment]
This was fix in v6.2.1 pushed to GitHub few minutes ago.
As usual, it will take 4 to 8 days to be available also from F-Droid, I will let this ticket opened in the meantime.

**Comment by xi7** [comment]
https://user-images.githubusercontent.com/67331785/161387164-ba713ae8-3208-4a59-b4df-63f56b8aec2b.mp4

sometimes crash

**Comment by UserNameM3** [comment]
For me it crashes when typing the third letter of searched item, it doesn't matter which one. For example typing abc the c would crash the launcher.

**Comment by UserNameM3** [comment]
For me version 6.2.1 doesn't fix the aforementioned issue. Searching still crashes the launcher.

**Comment by comradekingu** [comment]
Same here.

**Comment by falzonv** [comment]
Ok thank you all for the reports!

I think I was able to find the new bug (it is not the same that the one fixed in v6.2.1).
Actually I think this bug was already present since the Search was implemented, it was just never noticed...

I will soon publish an updated release v6.2.2.

**Comment by falzonv** [comment]
v6.2.2 was pushed to GitHub few minutes ago.
As usual, it will take 4 to 8 days to be available also from F-Droid, I will let this ticket opened in the meantime.

**Comment by UserNameM3** [comment]
Installed the 6.2.2 and the bug is gone, thank you for your awesome work.

**Comment by falzonv** [comment]
@UserNameM3:
Thank you for your kind words, I am glad you like Discreet Launcher :-)

**Comment by falzonv** [comment]
Since 11th April v6.2.2 is available on F-Droid so I will close this ticket.
