### ISSUE TITLE
Add double tap gesture to launch an app (like horizontal swipes)

### ISSUE THREAD

**Issue by falzonv** [falzonv/discreet-launcher#204]
This ticket is created following suggestion from @qguv in ticket #200:

> Currently, users can select an app to be run when they swipe left or right on the home screen. Would you consider making the double-tap gesture configurable in the same way? @r3veal could then configure the double-tap gesture to launch an app (of which there are several) whose sole purpose is to lock the screen. Other users could use it for other purposes, like firing a task in tasker.
>
>Is this something you'd consider @falzonv ?
>
>Thanks!

---

Interesting idea, I will think about it :-)

Note: actually what you described using a dedicated app can also be done with the current swipes (instead of "double tap to lock", it would be "swipe left/right to lock").

Best regards.

**Comment by falzonv** [comment]
Hello @qguv, @r3veal,

I am pleased to inform you that double-tap to open any app has been implemented/solved in new release v6.3.0!
This release has been published few minutes ago.

Here are the usual availability delays for each location:
- 4 to 8 days on F-Droid
- 0 to 2 days on Google Play
- Already available as direct APK on GitHub (https://github.com/falzonv/discreet-launcher/releases)

*Remarks:
I will leave this ticket opened until the release is effectively published on F-Droid.
You can use the export/import feature to switch from one version to another.*

Best regards.

**Comment by falzonv** [comment]
Hello @qguv, @r3veal,

Since Sunday v6.3.0 is available on F-Droid so I will close this ticket.

Best regards.

**Comment by qguv** [comment]
Just tried it out, and it's working great. Thanks a lot @falzonv!
