### ISSUE TITLE
you can make it so that you can create folders here and drag icons or folders with your finger. example:

### ISSUE THREAD

**Issue by sdfsd2** [falzonv/discreet-launcher#206]
![photo_2022-04-11_03-16-37](https://user-images.githubusercontent.com/102774950/162646235-1b8b9041-2372-4cc1-9fa4-ffa4b187aefc.jpg)
![photo_2022-04-11_03-16-42](https://user-images.githubusercontent.com/102774950/162646237-51ac8107-8053-4505-98a5-5f21fce75d8c.jpg)

**Comment by n-ce** [comment]
On behalf of @falzonv I'd assume a lot of things and say that this would probably increase the complexity of the app codebase and go beyond the minimal scope of this project. So this could always have been implemented but it has not been because of the nature of the app.

I Apologize if I'm wrong.

**Comment by falzonv** [comment]
Hello,

Thank you @sdfsd2 for the suggestion.

You are totally right @n-ce and thank you very much for having answered :-)

To be honest, I should also say that it's not something I am able to implement and maintain in a resource efficient way (drag and drop of icons and all the related visual effects).

Best regards.
