### ISSUE TITLE
folder mini icons bug

### ISSUE THREAD

**Issue by xi7** [falzonv/discreet-launcher#207]
https://user-images.githubusercontent.com/67331785/162828775-b7cd11d4-7304-410f-ba8e-0e954c16cabc.mp4

icons replicating, no pack.

**Comment by falzonv** [comment]
Hello,

Thank you for the report, I will have a look!
It seems to apply only to folders, and it is also strange that they start with no icon at the beginning.

Best regards.

**Comment by falzonv** [comment]
Hello,

This has been solved in new release v6.3.0!
I will leave this ticket open until it is available on F-Droid (usually takes 4 to 8 days).

Best regards.
