### ISSUE TITLE
Folders: option for circular shape instead of house shape

### ISSUE THREAD

**Issue by falzonv** [falzonv/discreet-launcher#209]
On Google Play, a user asked if it would be possible to use a circular shape instead of the current house shape for folders.

I have to try, this could be an interesting option if this is possible.

Some remarks about it:
- It would be a global setting applying to all folders at the same time (either all "house" or either all "circular")
- Default value would stay the house shape to not affect existing users
- Circular shape would be a simple circle with the number of apps in the middle, color should be customizable per folder like for the current house shape

**Comment by jcperil** [comment]
[Shade Launcher](https://github.com/amirzaidi/Shade) used to have these icon shapes: Square, Rounded square, Squircle, Circle, Cylinder and Teardrop.

![icon_shapes](https://user-images.githubusercontent.com/89805719/187025122-272c400c-2ec1-459e-9f51-d6b9c6b43d4a.jpg)

I thought I should mention it. All the shapes except teardrop look alright and could cater to a larger audience.

**Comment by falzonv** [comment]
Hello,

Finally had some time to test this and I will not implement it because in the long run it would add a lot of code complexity and potential bugs as users will (legitimately) ask for new shapes, customization per folder instead of global, etc.
This is not something I will have the time to manage so I prefer to keep Discreet Launcher simpler.

Best regards.
