### ISSUE TITLE
Alternative concept of ordering elements

### ISSUE THREAD

**Issue by bmivzkrp** [falzonv/discreet-launcher#211]
Could we suggest an alternative concept of moving items that would be more convenient for some blind users?
What it looks like now:
1. I open the Favorites;
2. I put my finger on the item I want to move (let it be the F-Droid). TalkBack announces its name;
3. For example - I want to move it one element higher, swapping it with Sound Recorder. I touch the F-Droid twice, hold my finger for a while, then start moving my finger up. When TalkBack tells me F-Droid, it means to me that I can remove my finger. This is not a mistake, that is, when TalkBack tells me the name of the item I m moving, it means that if I remove my finger, that item will swap places with another item.
I m happy with the current state of affairs, because I don t have a big list of favorite applications. But if the list of favorite applications is large enough, it will be quite difficult to organize the elements.
I suggest the following:
1. In the context menu of each element, there is a submenu Actions;
2. In this submenu, there are items Move above. If the user activates it, then the element he moves changes places with the one above;
3. If the user activates Move below, then the item he moves changes places with the one below;
4. If the item is at the top of the list, there is no Move above menu item. Also, if the item is last in the list, there is no Move below item for it.
I will be grateful for your attention to my request, and I apologize for my poor English.

**Comment by falzonv** [comment]
Hello,

Thank you for the suggestion and your interest in Discreet Launcher!

At first reading, I wonder if opening a context menu (which is usually done with a long press) could conflict with how the drag and drop process is implemented.
I will have a look and try to think about another option if the context menu doesn't work as expected.

Just so that you are not surprised, I should mention that it will probably take a long time as I am currently very busy with my job.

Best regards.

**Comment by bmivzkrp** [comment]
No, everything works properly there. It s just that the current concept 
is not very convenient for blind users, and I think we need an 
alternative. Moving works, and the context menu also works when using 
TalkBack or Jieshuo. Just when working with applications, a blind user 
uses a double touch as opposed to a seeing user who uses a single touch. 
Although I don t know how all this has changed in the latest versions of 
Android, as it already supports multi-finger gestures for accessibility.

04.05.22 19:32, Vincent Falzon пише:
> Hello,
> 
> Thank you for the suggestion and your interest in Discreet Launcher!
> 
> At first reading, I wonder if opening a context menu (which is usually done with a long press) could conflict with how the drag and drop process is implemented.
> I will have a look and try to think about another option if the context menu doesn't work as expected.
> 
> Just so that you are not surprised, I should mention that it will probably take a long time as I am currently very busy with my job.
> 
> Best regards.
>

**Comment by bmivzkrp** [comment]
Here is another alternative concept:

1. The user in the context menu, selects, for example, Move below;

2. He again gets to the list of items;

3. Focuses on the element below which he wants to place the element he needs;

4. The user touches this item;

5. The item that the user moves is below the item that the user touched.

Similarly, when the user selects Move above in the context menu.

**Comment by falzonv** [comment]
Hello,

Thank you for the additional explanations and suggestion :-)
I didn't had the time yet to start looking into this to be honest...

Best regards.

**Comment by falzonv** [comment]
Hello,

This has been a long time but, good news, this will be implemented in the next release!

I implemented what you suggested in your first post but I changed it a bit to get `Move before "app1"` and `Move after "app2"`, with "app1" and "app2" the name of the apps respectively before and after the selected one.
The first and last apps in the list of favorites will display only the relevant option, as described in your step 7.

Best regards.

**Comment by bmivzkrp** [comment]
I just got 6.4.0. I can t find the functionality you described because 
the context menus don t have it.

**Comment by falzonv** [comment]
Hello @bmivzkrp,

Sorry for the late reply, I was off last weeks.

When you open the page to order favorites by drag and drop, if you long press an item in the list a context menu should appear with options to move the item upwards or downwards (if this is not the first/last item of the list).
I just tested on my phone and for me it appears as expect.
This doesn't work for you?

Best regards.

**Comment by bmivzkrp** [comment]
@falzon
v Did you check it with TalkBack? I suspect it might work if I turn off the screen reader. But I can t do that because I m completely blind.
I can only open the context menu from the favorites drawer. By the way, it would be nice to add the ability to organize elements there.
In the list of favorite applications, which we can get to, for example, by activating the Discreet Launcher icon in the list of applications and then activating Favorites, everything is left as is.

**Comment by bmivzkrp** [comment]
@falzonv 
Please excuse me. I guess I didn t think the concept through properly when I proposed it. This currently does not work for blind users as it conflicts with the normal way to move items. Could you do it differently?
Next to each item in the list should be a button called, say, the "Action Menu". If we click on it, a list of actions appears.
It is better to do it this way, because otherwise the user will have to change the settings of the screen reader.
I apologize once again for my carelessness.

**Comment by falzonv** [comment]
Hello,

Ok no worries, I will have a look on how to change this from the current long press towards a dedicated button.
However I am quite busy at the moment so the next release will probably not be before september...

Best regards.

**Comment by falzonv** [comment]
Hello,

I have just published a new release v6.5.0 with a different way of doing it which, hopefully, should work for both blind and non-blind users while not conflicting with the normal way to move items.

There are now two arrows for move up and move down next to each item (except first and last items which are special). For these arrows, the field `contentDescription` that should be read by TalkBack (if I understood properly) is filled with a relevant text such as *"Move before (the name of the app above)"* or *"Move after (the name of the app below)"*.

Before implementing this, I also tried with a simple button opening at list of actions. It works of course but I am afraid this would confuse non-blind users by sort of "hiding" that you can simply move the items to reorder the list (if people see a button they may not think other parts are clickable). It's kinda the same with arrows but at least the user experience is more efficient, and even for blind users it should save a couple of clicks.

This ticket will stay open at least until v6.5.0 is available on F-Droid (usually takes 4 to 8 days).

Best regards.

**Comment by bmivzkrp** [comment]
@falzonv 
Many thanks.

**Comment by bmivzkrp** [comment]
@falzonv
Did you check it with TalkBack? I suspect it might work if I turn off 
the screen reader. But I can t do that because I m completely blind.
I can only open the context menu from the favorites drawer. By the way, 
it would be nice to add the ability to organize elements there.
In the list of favorite applications, which we can get to, for example, 
by activating the Discreet Launcher icon in the list of applications and 
then activating Favorites, everything is left as is.

12.08.22 23:41, Vincent Falzon пише:
> Hello @bmivzkrp,
> 
> Sorry for the late reply, I was off last weeks.
> 
> When you open the page to order favorites by drag and drop, if you long press an item in the list a context menu should appear with options to move the item upwards or downwards (if this is not the first/last item of the list).
> I just tested on my phone and for me it appears as expect.
> This doesn't work for you?
> 
> Best regards.
>

**Comment by bmivzkrp** [comment]
OK. Once I get the update I ll look into it. If I have no comments, I 
will close this issue.
Thank you so much for not ignoring accessibility.

19.07.22 21:43, Vincent Falzon пише:
> Hello,
> 
> This has been a long time but, good news, this will be implemented in the next release!
> 
> I implemented what you suggested in your first post but I changed it a bit to get `Move before "app1"` and `Move after "app2"`, with "app1" and "app2" the name of the apps respectively before and after the selected one.
> The first and last apps in the list of favorites will display only the relevant option, as described in your step 7.
> 
> Best regards.
>
