### ISSUE TITLE
break column fav

### ISSUE THREAD

**Issue by xi7** [falzonv/discreet-launcher#212]
![FAV](https://user-images.githubusercontent.com/67331785/165952984-52d26b5a-790a-4f65-a3cb-19b5c318f6e5.jpg)

-actual is just mixed list between (ex: picture) fav+tools+games, we can make folder and send to fav but with separator the organization will be better there.

-scenery w/o label.

**Comment by falzonv** [comment]
Hello,

Thank you for the suggestion but this is not something I will implement.
It would introduce too much code complexity and potential maintenance issues.

Best regards.

**Comment by xi7** [comment]
![Screenshot_2022-05-04-15-40-27](https://user-images.githubusercontent.com/67331785/166804049-ad3663f7-de54-4e93-bc5a-7547891be989.png)

add that first bar will change all code structure ?  (this bar break column / row )

**Comment by falzonv** [comment]
> add that first bar will change all code structure ? (this bar break column / row )

Yes
