### ISSUE TITLE
Adding wallpaper?

### ISSUE THREAD

**Issue by FlutterFraz** [falzonv/discreet-launcher#224]
Hello,
I've been using your app for some time now and the only thing I miss is my wallpaper. I tried to find something already existing but it I couldn't find anything so here I am: is this idea trivial?

**Comment by FlutterFraz** [comment]
My god, just had to change it from the system settings.....

**Comment by falzonv** [comment]
Hello,

Thank you for using Discreet Launcher :-)

Changing the wallpaper is indeed not included because it requires additional permissions and most gallery apps already provide this feature in a more convenient way than I could ever do (option "Set as" when viewing a picture).

Best regards.
