### ISSUE TITLE
[feature idea] Add text to launcher home screen?

### ISSUE THREAD

**Issue by gbdomubpkm** [falzonv/discreet-launcher#226]
An option allows to add text on the lock screen (seen this with android 11). Would it be possible to have an option to add (a few lines of) text on the launcher splash screen below the time and date? Memory aid, thought of the day..
![Add text](https://user-images.githubusercontent.com/50362604/170700888-74f3f645-9521-4033-8042-aa27553c0e61.png)

**Comment by falzonv** [comment]
Hello,

Thank you for the suggestion!

Maybe something could be done with a static text (which could be configured in the settings) displayed below the clock (position top/middle/bottom would apply to both at the same time), but that seems a bit more limited than what you may expect...
Thought of the day would probably require the Internet connectivity permission, which is not good in my opinion.

Note: although this is not the same concept, it remind me of an app called Mindful Notifier (https://f-droid.org/fr/packages/com.kmac5dev.mindfulnotifier or https://github.com/kmac/mindfulnotifier).

Best regards.

**Comment by gbdomubpkm** [comment]
Hello.
Thanks for picking up the idea.
Thanks also for your F-Droid links. However, this does not meet my immediate expectations.
Regarding my suggestions, I know that you will do the best as always.
For 'the thought of the day' it is simply a term that I use to designate for example a philosophical thought written manually and visible on the launcher 🙂 so, in my idea, I was not referring to an internet connection .
Have a good day.
Best regards
