### ISSUE TITLE
Request Features : Double tap to wake, double tap to sleep/lock

### ISSUE THREAD

**Issue by clues4me** [falzonv/discreet-launcher#239]
Hello dev,

Thank you for the best clean launcher, this is great job.
Mind if I request double tap to wake/sleep/lock, because my phone supported through system setting but somehow doesnt work while running this laucher.
Thanks before.

Regards.

**Comment by falzonv** [comment]
Hello,

(Sorry for the late reply, I was away last weeks.)

I am glad you like Discreet Launcher, thank you for your message :-)

Regarding the double tap to sleep/lock, as I mentioned in https://github.com/falzonv/discreet-launcher/issues/48#issuecomment-854896343, https://github.com/falzonv/discreet-launcher/issues/161#issuecomment-989733267 and https://github.com/falzonv/discreet-launcher/issues/200#issuecomment-1076701903, this requires a special admin permission and will not be implemented directly in Discreet Launcher.

However, in ticket #200 a user suggested the following...

> **qguv:** Currently, users can select an app to be run when they swipe left or right on the home screen. Would you consider making the double-tap gesture configurable in the same way? @r3veal could then configure the double-tap gesture to launch an app (of which there are several) whose sole purpose is to lock the screen. Other users could use it for other purposes, like firing a task in tasker.

...and the double tap gesture to open a user-defined app was added in v6.3.0 (#204).
Well, this requires another app to manage the sleep/lock part (never tested any) but can probably be a decent workaround.

---

By the way, looking again in ticket #48, I see that I also wrote:

> By the way, while searching, I came across an app called "Easy Lock" which may interest you because it even has a mode "double tap to sleep from any application":
https://forum.xda-developers.com/t/app-4-0-material-easy-lock-double-tap-status-bar-nav-bar-to-sleep.3222024/
>
> *Disclaimer: I have not tested this application (only looked at its [source code](https://github.com/aravindsagar/EasyLock) to check permissions and the way to go in sleep mode) and many users report that it doesn't work perfectly for them (for example after the phone is in sleep mode they cannot unlock with the fingerprint, have to use another method).*

The disclaimer is still true (never tested the app myself, only looked a small part of the code, potential bugs, etc.), but you may still be interested by the app so I mention it just in case.

Best regards.
