### ISSUE TITLE
hide the app search button

### ISSUE THREAD

**Issue by daboudii** [falzonv/discreet-launcher#241]
**What solution would you like ?**
It would be nice to have an option in settings to hide the search button, in case you have a very limited amount of app.

**Comment by falzonv** [comment]
Hello,

This already exists since v5.0.0, added in #91 :-)
If you do a long press on the search icon, there is a shortcut to the "Hidden apps" menu where you can select it.

Best regards.

**Comment by daboudii** [comment]
I didn't think of the "Hidden apps" menu but it make sense. 

Thank you!
