### ISSUE TITLE
Too small icons

### ISSUE THREAD

**Issue by lianergoist** [falzonv/discreet-launcher#249]
I use v6.6.1.

I get too small icons on my Lenovo Tab M10 Plus tablet with android 12 (1200x2000). 

<img src="https://user-images.githubusercontent.com/6023573/199460239-e15c6a1d-7200-4817-bad4-c5fab58c00ad.jpg" width="50%"/>
<img src="https://user-images.githubusercontent.com/6023573/199460288-2ec5c381-f606-4aa1-9370-3c2688b015f7.jpg" width="50%"/>

**Comment by falzonv** [comment]
Hello @lianergoist,

Thank you for the report.

Discreet Launcher was mainly designed for mobile phones so indeed this looks a bit out of proportions on a tablet.
I will have a look to see how the icons display can be improved on tablets.

Best regards.

**Comment by falzonv** [comment]
Hello,

I am pleased to inform you that (as you probably saw from the translation update) a new icon size setting has been added in new release v7.2.0!
This release has been published few minutes ago.

Here are the usual availability delays for each location:
- 4 to 8 days on F-Droid
- 0 to 2 days on Google Play
- Already available as direct APK on GitHub (https://github.com/falzonv/discreet-launcher/releases)

*Remarks:
I will leave this ticket opened until the release is effectively published on F-Droid.
You can use the export/import feature to switch from one version to another.*

Best regards.
