### ISSUE TITLE
Hide the text "Applications (list from ...)"

### ISSUE THREAD

**Issue by falzonv** [falzonv/discreet-launcher#25]
This ticket is opened following #24, from @tuch96 to follow this point:

> A function to deactivate the top text "Applications (List....)" in the app overview.

---

Ok for me to implement this new setting, I will see how to do it and keep you updated.

**Comment by falzonv** [comment]
Hello @tuch96,

After further thinking, I wonder if this text "Applications (list from ...)" is still needed at all.
Maybe instead of create a new setting we could simply remove it.

In the firsts versions of the launcher, the list was not updated automatically when an application was added or removed (it had to be done with the menu entry), so it was useful to see the last time it was refreshed in this text.

But now the update process works quite well on all relevant events (application added or removed, icon pack changed, web shortcut added or removed) so this text is probably not needed anymore.

What do you think about removing it?

Best regards.

**Comment by falzonv** [comment]
Yes it definitely looks cleaner without the text and it also make some parts of the code simpler, I will remove it in the next release.

**Comment by falzonv** [comment]
Hello,

The new release v3.0.0 has been pushed to the stores few minutes ago and the usual publishing delay is:

- 0 to 2 days for Google Play
- 4 to 8 days for F-Droid

*Note: I will leave this ticket opened until the release is effectively published on both stores.*

Best regards.

**Comment by falzonv** [comment]
Hello,

This release being now available on F-Droid, I will close this ticket.
Feel free to add comments if needed :-)

Best regards.

**Comment by AeOeAa** [comment]
This works great. However, it's not completely transparent when the list refresh / update is happening. In combination with folders and favourites, sometimes a manual refresh is needed for the items to show as expected.

**Comment by falzonv** [comment]
Hello,

There should always be a message "Applications list refreshed" displayed for a few moments each time the applications list is refreshed (no refresh happens without this message being displayed because it is included at the end of the process).
=> Maybe this is something that should be clarified in the Help section? (will add it to ticket #34)

Regarding the combination folders/favorites, it may be due to the bug from ticket #33 that you discovered previously.

Best regards.

**Comment by AeOeAa** [comment]
Great, that makes sense 👍
