### ISSUE TITLE
Reordering contents favourites and folders

### ISSUE THREAD

**Issue by tonysidaway** [falzonv/discreet-launcher#254]
At present the ordering of app lists, particularly favourites and folders, appears difficult to control. A drag function would enable the user to easily arrange the apps into their desired order.

**Comment by falzonv** [comment]
Hello @tonysidaway,

Thank you for the suggestion, however this is not something I am able to implement (would add too much code complexity related to the time I have to maintain the app).

Favorites can already be arranged in any order using drag and drop from the menu entry "Favorites".
I agree this is not as convenient as doing it directly from the home screen, but favorites are not expected to change every day so this stays quite acceptable.

Some other information regarding ordering:
- When an app is added to favorites, it is added to the end of the list.
- Folder contents and the main app list are ordered alphabetically, so an app can be renamed to have a different place there.

Best regards.
