### ISSUE TITLE
New setting to disable the texts under the app icons

### ISSUE THREAD

**Issue by falzonv** [falzonv/discreet-launcher#26]
This ticket is opened following #24, from @tuch96 to follow this point:

> It would be great to disable the texts under the app icons.

---

Yes it could even be a setting with 3 options allowing to display (a) "Icons and texts", (b) "Icons only" or (c) "Texts only".
The default value would be "Icons and texts" as it is today.
I will see how to do it and keep you updated.

**Comment by falzonv** [comment]
Hello @tuch96,

Previously I suggested:

> it could even be a setting with 3 options allowing to display (a) "Icons and texts", (b) "Icons only" or (c) "Texts only"

After some tests, the "Texts only" option looks like a mess and it would take too much changes in the code to improve this (and even when doing this changes, the "Icons+Text" or "Icons only" views would still look much better).

**Conclusion:** I will add only the setting to hide the texts under the icons (as you initially requested).

Best regards.

**Comment by tuch96** [comment]
That's ok! And a great solution for a simple display of the app icons within the central app overview. Perfect!

**Comment by falzonv** [comment]
Hello,

I am pleased to inform you that this feature has been implemented in release v3.2.0!

This new release v3.2.0 has been pushed to the stores few minutes ago and the usual publishing delay is:

- 0 to 2 days for Google Play
- 4 to 8 days for F-Droid

*Note: I will leave this ticket opened until the release is effectively published on both stores.*

Best regards.

**Comment by tuch96** [comment]
That looks very good! I have taken a few screenshots. I have now deleted my old launcher and only use Discreet Launcher!! I also have a few more ideas for the usability... if you want :-). 

![Screenshot_20210501-203624_Discreet_Launcher](https://user-images.githubusercontent.com/57192210/116792036-a2657b80-aabe-11eb-864e-e2dd89c967f5.png)
![Screenshot_20210501-203605_Discreet_Launcher](https://user-images.githubusercontent.com/57192210/116792041-aabdb680-aabe-11eb-9e42-5e03c990b4e0.png)

**Comment by AeOeAa** [comment]
If one is familiar with one's apps ;)

However, until there's a solution to the folder icons issue, I'm not going to be using this feature 😀

![Screenshot_20210502_080752](https://user-images.githubusercontent.com/13118178/116804276-d6bc5480-ab1d-11eb-8cf8-d8dcbdbb0733.jpg)

**Comment by falzonv** [comment]
Hello @tuch96,

Thank you very much for you feedback and screenshots, I am glad you like the launcher!

> I also have a few more ideas for the usability... if you want :-)

=> Yes sure! They may or not be implemented but all ideas are welcome :-)
I will close this ticket (since it is solved) but feel free to create new one(s)! (or reuse ticket #31 which I created by mistake)

---

Indeed @AeOeAa, it looks quite confusing on your screenshot!
Starting soon to work on ticket #35, for information ;-)

Best regards.

**Comment by AeOeAa** [comment]
I suggest this feature to only encompass app icons (as the original idea: "disable the texts under the **app** icons" and the issue heading which is a bit more ambiguous now: "show only apps icons")

Alternatively an option to allow folder icons to keep their text labels when the setting to hide the texts under the icons is on.

**Comment by falzonv** [comment]
Hello @AeOeAa,

Thank you for your suggestion, I agree this is a better and simpler solution than what I proposed in #35.
I will implement this and reopen this ticket for follow-up.

> Alternatively an option to allow folder icons to keep their text labels when the setting to hide the texts under the icons is on.

=> Yes perhaps in the future, but I will start as you suggested by only hiding the text for apps (because if the user disable this option we will be back at the original problem that the folders look all the same).

Will also rename this ticket for clarity ;-)

Best regards.

**Comment by falzonv** [comment]
Ok, this is corrected and will be in v3.4.0.
For clarity, I also added a small explanation text below the option to hide apps names (emphasizing that folder names will be kept).

**Comment by falzonv** [comment]
Hello,

I am pleased to inform you that new release v3.4.0 has been published!

Here are the usual availability delays for each location:
- 4 to 8 days on F-Droid
- 0 to 2 days on Google Play
- Already available as direct APK on GitHub (https://github.com/falzonv/discreet-launcher/releases)

*Remarks:
I will leave this ticket opened until the release is effectively published on F-Droid.
You can use the export/import feature to switch from one version to another.*

Best regards.

**Comment by falzonv** [comment]
Since yesterday v3.4.0 is now available on F-Droid so I will close this ticket.
