### ISSUE TITLE
Long-press shortcut

### ISSUE THREAD

**Issue by comradekingu** [falzonv/discreet-launcher#266]
Press open area of menu, get additional configurable shortcut?

**Comment by falzonv** [comment]
Hello and happy new year!

I am note sure to understand your suggestion.
Could you elaborate a bit?

Best regards.

**Comment by comradekingu** [comment]
So I was thinking a fourth shortcut was possible by long-pressing an open area.
Right now the other shortcuts are swipe left, swipe right, and double-press.

**Comment by falzonv** [comment]
Hello,

Ok, thank you for the clarification.

Actually the long press is already used for a different purpose, related to the immersive mode setting:
In immersive mode the status and navigation bar disappear, but they appear again when the user performs some actions such as opening the notification drawer. The long press allows the user to immediately re-enter in immersive mode (that is, with the status and navigation bars hidden).

Best regards.
