### ISSUE TITLE
Restore original name after renaming app

### ISSUE THREAD

**Issue by jcperil** [falzonv/discreet-launcher#274]
Let's say, you rename an app.

<img src="https://user-images.githubusercontent.com/89805719/218353749-c1800749-f9ed-4b87-931a-80a59f31b89e.jpg" height="300px"/>

Should there be an option to restore original name of the app?

**Comment by falzonv** [comment]
Hello,

Currently, when you empty the editable field containing the app name, the original name appears in background of the field and can be restored by validating the (now empty) field.
I am not sure if this enough, maybe it can be improved...

Best regards.

**Comment by jcperil** [comment]
Thank you. I was not aware of this. I consider it solved. Please close this issue as you see fit.
