### ISSUE TITLE
[Bug?] Color picker doesn't update when manually inputting #RRGGBB values.

### ISSUE THREAD

**Issue by vXIVx** [falzonv/discreet-launcher#280]
This was recorded on Android 12/13, but this issue has persisted all the way down to android 8.
Manually putting the #RRGGBB value doesn't save and doesn't update the preview either.

(Apologies for the terrible gif, the webm was too large.) 
<img alt="Discreet Launcher - color picker manual input issue" src="https://user-images.githubusercontent.com/21109730/220502334-54350620-4458-4cfd-89a9-3324d892fd4e.gif" width="50%"/>

**Comment by falzonv** [comment]
Hello,

Thank you for the report!
Did you try to validate the manual color input by pressing "Done" on the keyboard? (I don't see it in the video)

It is this step which applies the new color to the preview, allowing to adjust the transparency before pressing "Apply" (the button "Apply" will always validate the color displayed in the preview).

Best regards

**Comment by vXIVx** [comment]
Yes, after actually pressing the done/checkmark on the keyboard it updates. 

My bad, I guess I'm just used to the behavior that the buttons automatically accept the new values after clicking on them.
