### ISSUE TITLE
One-time launch from the Hide/Unhide menu

### ISSUE THREAD

**Issue by opk12** [falzonv/discreet-launcher#290]
When I occasionally need a hidden app, I must go to the Hide/Unhide menu twice (once to unhide, once to hide). What about allowing to launch the app directly from the menu (so I don't have to hide the app again after using it)? I don't want to suggest feature creep in a minimalist launcher though, so I'm not sure.

**Comment by falzonv** [comment]
Hello,

Sorry but this won't be implemented as the hidden apps feature of Discreet Launcher is only intended for bloatware apps that cannot be disabled.
If you regularly need an hidden app, maybe it shouldn't be hidden in the first place?

Best regards.
