### ISSUE TITLE
add support for Widgets [feature request]

### ISSUE THREAD

**Issue by Shkzeen** [falzonv/discreet-launcher#291]
Hello!
as y'all know discreet doesn't have support for Widgets.. and due to an unfortunate series of events the default launcher broke with an update (Thanks MIUI) and I kinda need Widgets.
but recently I came across an app called taskbar which implements Widgets in a way that I think would fit the way the design language of discreet quite nicely.
 the code is on farmerbb's github https://github.com/farmerbb/Taskbar
Thanks for reading!

**Comment by falzonv** [comment]
Hello @Shkzeen,

Sorry for the late answer, I am very busy with my job these months and hadn't checked GitHub since a long time...

I do not plan to implement widgets support as it would require additional permissions, move away from the idea of having an empty home screen and add too much code complexity and potential bugs for the time I now have to maintain this project.

However, I just tried Taskbar (very nice app indeed) and it seems quite compatible with Discreet Launcher so the best option in that case may be to use Discreet Launcher + Taskbar.

Best regards

**Comment by Shkzeen** [comment]
Hello @falzonv!
I really ,really am sorry for not reading your response earlier..
I'm really happy for you and the fact that you got a (hopefully!) stable income source. =D
However seeing such a great launcher being left in the dust is kind of a bummer. 
Tried learning java in an attempt to help but failed miserably. XD
I think adding it as an ***EXPERIMENTAL*** only icon (an icon such as search) that users would acativate at their own risk that opens a window closer to what is seen in the aforementioned taskbar application would be quite fitting.
Sorry for the long message.. I re-read my issue and found it to be quite unclear. I understand your point of view and the fact that *open source does NOT mean the developer is obligated to do what the uaser says*.
Again, Sorry for making this comment too long.

**Comment by Shkzeen** [comment]
Hello @falzonv!
I really am sorry for not reading your response earlier..
I'm really happy for you and the fact that you got a (hopefully!) stable income source. =D
However seeing such a great launcher being left in the dust is kind of a bummer.
Tried learning java in an attempt to help but failed miserably. XD
consider adding it as an **EXPERIMENTAL** icon (an icon such as search, folders,etc..) that users would acativate at their own risk that opens a window closer to what is seen in the aforementioned taskbar application as that would be quite fitting for what it'll hopefully be.
Ps. Sorry for the long message.. I re-read my issue and found it to be quite unclear. I understand your point of view and the fact that ***open source does NOT mean the developer is obligated to do what the user asks for***.
Sorry for making this comment too long.

**Comment by falzonv** [comment]
Hello,

> seeing such a great launcher being left in the dust is kind of a bummer

That sounds a bit harsh considering I still managed to publish one release every 2-3 months in the last year.
For sure when I had more time to work on it there was often several releases per month, but life happens and this is not the case anymore. Still, maybe we should wait a 1-year old last release before calling it "being left in the dust"?

> consider adding it as an EXPERIMENTAL icon (an icon such as search, folders,etc..) that users would activate at their own risk that opens a window closer to what is seen in the aforementioned taskbar application as that would be quite fitting for what it'll hopefully be.

Even though labeling it experimental will not make it less complex to implement, the idea of putting widgets behind an icon like search and folders to not interfere with the empty home screen concept is quite interesting and worth an investigation.

I will make no promises to implement it, but I will try to have a look in the coming weeks/months (which may be disappointing to read, but as I wrote, labeling it experimental neither removes the complexity or increases my available time...).

Best regards.

**Comment by jrcarter** [comment]
My thinking is that you could offer a "widget page" as an option for swipe right or swipe left. That would allow widgets without cluttering up the home screen. I have no idea how much effort would be involved.

My personal interest is in the AF Weather Widget.

**Comment by Shkzeen** [comment]
@jrcarter 
>as an option for swipe right or swipe left.
Adding it as an icon would do the same thing. Remember that you can set the Swipe Left/Right & Double tap shortcuts in the 'Operation' menu (wrench on favorites bar/ tap discreet's icon) 
btw what is that menu officially called? (perhaps an action menu??) @falzonv

**Comment by xi7** [comment]
widgets no need android permission and best solution is unlimited side bar keeping context discreet launcher.

like this launcher.

https://play.google.com/store/apps/details?id=com.rcmz.chromalauncher

**Comment by falzonv** [comment]
Hello,

Thank you for the suggestions but actually no more new features or options will be implemented in Discreet Launcher. Only maintenance releases to fix bugs and maintain compatibility with new Android versions will continue.
You can find more details in ticket [#314](https://github.com/falzonv/discreet-launcher/issues/314).  

Best regards.
