### ISSUE TITLE
Option to default to hiding new apps

### ISSUE THREAD

**Issue by opk12** [falzonv/discreet-launcher#293]
I use the system launcher by default. I run Discreet Launcher manually, when I need to be distraction-free. So I have hidden almost all apps and shortcuts in Discreet, but not in the main launcher. When I install a new app, it is visible in Discreet by default and I hide it manually. What about auto-hiding new entries by default?

**Comment by falzonv** [comment]
Hello,

Sorry but I don't see the point of hiding all apps in the launcher.
The hidden apps feature of Discreet Launcher is only intended for bloatware apps that cannot be disabled.

Best regards.
