### ISSUE TITLE
Possible bug with split screen and recent apps

### ISSUE THREAD

**Issue by falzonv** [falzonv/discreet-launcher#298]
Creating this ticket following a comment from @nanerc3 in another (unrelated) ticket:

> hello
>
> Since there is no other place to write sentences, I will report a bug even though it is v7.2.0
>
> It seems that the history screen was accidentally split screen and the upper app was deleted
After that, only the top third of the history screen is displayed on the bottom of smartphone screen
>
> After that, I returned to the home app that was originally included in the smartphone and fixed it by tampering with the division, but I will just report it

**Comment by falzonv** [comment]
Hello @nanerc3,

Thank you for the bug report!

However, since the Recent Apps screen and the split-screen features are both managed by the system (Discreet Launcher does nothing special to them), I am afraid the options to investigate are quite limited...

Usually the split-screen is triggered following a user action (sometimes an accidental action, but still a user action).
=> Which sequence of actions allows to reproduce the bug you noticed?

I tried to reproduce it on my phone (LineageOS 18.1, based on Android 11) by opening the Recent Apps screen and splitting it but everything works as expected (I have the app above, the Recent Apps screen below, and the split bar works normally).

Also, it seems that on some devices the Recent Apps screen doesn't work properly with custom launchers (only works well with the factory launcher).
=> Do you observe the same issue with other custom launchers?

Best regards.

**Comment by nanerc3** [comment]
Thank you for reply

However, as I wrote before, I accidentally switched to split screen, and when I hurriedly tried to return to the original single screen, the upper app disappeared for some reason And unfortunately I can't reproduce it

Currently, my smartphone has 8 custom launchers other than DL, but I don't know how to reproduce the bug as mentioned above, so I don't know if the same thing will happen with these

Moreover, it seems that it was a bug that should have been reported to Google, and I apologize for wasting your time on this matter
