### ISSUE TITLE
[feature request] dynamic icons

### ISSUE THREAD

**Issue by Shkzeen** [falzonv/discreet-launcher#299]
Hello,
some icon packs offer multiple icons for some apps that can be stitched together into an adaptive icon (eg: clock moves with time, calendar day changes, etc..)
an example of such icon pack is https://f-droid.org/packages/com.donnnno.arcticons/
Thank you.

**Comment by falzonv** [comment]
Hello,

Thank you for your suggestion, I didn't know these types of dynamic icons existed.

Unfortunately this will not be compatible with how Discreet Launcher works internally: to minimize resources consumption and allow immediate display of the app drawer even on old devices, the list of apps and their icons are retrieved only on some events (launcher start, install/remove app, switch icon pack, etc.) so things requiring real-time update of the icons (such as dynamic icons or notification dots) will not work with this launcher.

Remarks: even though its dynamic icons won't work, the Arcticons icon pack can still be used with Discreet Launcher.

Best regards
