### ISSUE TITLE
swipe left - right / skills

### ISSUE THREAD

**Issue by xi7** [falzonv/discreet-launcher#30]
swipe left - right

swipe show clock (with seconds) ->
swipe show calendar ->
swipe show network  ->
swipe show thermal ->
swipe show cpu / memory / disk ->
swipe hide ->

what do u think, clock is enough ?

**Comment by falzonv** [comment]
Hello,

To be honest, I think that for a minimalist distraction-free offline launcher it mostly adds complexity and unnecessary permissions (access to calendar is not good from privacy point of view, access to network contradicts working offline, maybe other permissions are needed for thermal/cpu/memory/disk, something looking like several home screens with swipe left/right would add lots of distractions which goes opposite to the goal of this launcher).

Sorry, I will not implement this.

Best regards.
