### ISSUE TITLE
[feature/improvement request] ability to pan left and right to reveal more of the wallpaper

### ISSUE THREAD

**Issue by fingerpad** [falzonv/discreet-launcher#300]
if a wallpaper has a wider aspect ratio than the phone screen, then some portions of the wallpaper will be hidden. i got around this with other launchers by creating three blank homescreen pages and setting the center page as the main homescreen. with this method the wallpaper would be nicely centered, and i could swipe left or right to see the hidden portions of the wallpaper. however discreet launcher has only a single page homescreen.

swiping left or right to see more of the wallpaper would conflict with homescreen gestures, but since an uncluttered view of the wallpaper is one of the strengths of discreet launcher, i think this feature would be worth looking into.

**Comment by Shkzeen** [comment]
I'd suggest using the gyroscope of the device (if available) to pan the background depending on the orientation and/or movement.

Best regards.

**Comment by falzonv** [comment]
Hello,

Thank you for the suggestions but actually no more new features or options will be implemented in Discreet Launcher. Only maintenance releases to fix bugs and maintain compatibility with new Android versions will continue.
You can find more details in ticket [#314](https://github.com/falzonv/discreet-launcher/issues/314).  

Best regards.
