### ISSUE TITLE
[feature REQUEST] App shortcuts

### ISSUE THREAD

**Issue by Shkzeen** [falzonv/discreet-launcher#301]
Some apps (eg:termux) support [App shortcuts](https://developer.android.com/develop/ui/views/launch/shortcuts) long tapping them causes them to show some options accompanied with icons (eg: termux has a fallback mode that I found to be only accessible through this method) 
Thanks for reading!

**Comment by falzonv** [comment]
Hello,

Thank you for the suggestion but no more new features or options will be implemented in Discreet Launcher. Only maintenance releases to fix bugs and maintain compatibility with new Android versions will continue.
You can find more details in ticket [#314](https://github.com/falzonv/discreet-launcher/issues/314).

Regarding Termux failsafe, the first method described in the video https://www.youtube.com/watch?v=2y4nB_eBKPs should work regardless of the launcher (starting a failsafe session inside Termux).

Best regards.
