### ISSUE TITLE
Add apps into home screen

### ISSUE THREAD

**Issue by ghost** [falzonv/discreet-launcher#305]
Add apps into home screen

**Comment by Shkzeen** [comment]
Hello,
The whole point of discreet is to have a clean and sleek looking home screen.
Hope this helps!

Best regards.

**Comment by falzonv** [comment]
Hello,

Indeed, the purpose of this launcher is to have an empty home screen so no apps directly in the home screen.
(It seems the requestor deleted his account anyway)

Best regards.
