### ISSUE TITLE
[feature/improvement request] option to hide favorites

### ISSUE THREAD

**Issue by fingerpad** [falzonv/discreet-launcher#307]
i would like to be able to hide favorites in the same way that i can hide the app drawer.

**Comment by fingerpad** [comment]
ah nope. i mean an option for "no favorites", similar to the existing option "no app drawer". my fault. "always show favorites" is the opposite of what i meant.

**Comment by falzonv** [comment]
Hello,

Thank you for the suggestion but, as the favorites panel also holds the menu button, providing an option to hide this panel would put many users trying it in an embarrassing situation.

Best regards.
