### ISSUE TITLE
[Feature Request] Swipe actions

### ISSUE THREAD

**Issue by goblin535353** [falzonv/discreet-launcher#309]
Hello. I love the app. Can you please make swipe action customizable. For example on homescreen 'swipe down' to open notifications. Thank you.

**Comment by falzonv** [comment]
Hello,

Thank you for the suggestion but no more new features or options will be implemented in Discreet Launcher. Only maintenance releases to fix bugs and maintain compatibility with new Android versions will continue.
You can find more details in ticket [#314](https://github.com/falzonv/discreet-launcher/issues/314).  

Best regards.
