### ISSUE TITLE
Reduce space between app icon and text

### ISSUE THREAD

**Issue by falzonv** [falzonv/discreet-launcher#31]
This ticket was created by mistake, I will reuse it later when I have to create a new one.

**Comment by falzonv** [comment]
This ticket will be used to follow improvement suggestions from **xi7** and **AeOeAa** in ticket #11.
I put them back here for continuity and will answer in the next comment.

**xi7**:
> ![Screenshot_2021-05-04-19-19-36](https://user-images.githubusercontent.com/67331785/117077095-dd112300-ad0d-11eb-8662-363b6cebb148.png)
plz update remove the padding/margins between icon and text, need a lot space area screen
>
> also add visual feedback when click apps


**AeOeAa**:
> I noticed this too, **xi7**. It's especially clear when you have more lines of icons, then padding varies between lines of apps which looks odd.
>
> My two cents:
>
> It happens because of line break in the text below one or more of the icon(s) horisontal. Then the other icons with just one line of text will be moved down, appearing to have more padding between icon and text.
>
> For me, it happens more frequently with folder names because of the design choice of adding " (#)" to all titles, where # is the number of apps in the folder. I shortened some titles because of this. (renaming apps is probably not doable for most users, so there's no solution there)
>
> Are the labels aligned center to other labels, **falzonv**?

**Comment by falzonv** [comment]
Hello @xi7, @AeOeAa,

Ok to lower this space, I have included 6 screenshots below with various cases.
=> Could you please tell me your preference?

---

**The screenshot 1 shows the current situation.** Screenshot 2 reduces the padding between icon and text, and screenshot 3 completely removes this padding.

| 1/ Align center + Current space | 2/ Align center + Smaller space | 3/ Align center + No space |
| --- | --- | --- |
| ![2021-05-05_icon_text_space_5dp_center](https://user-images.githubusercontent.com/4698531/117172847-7acb2780-adcc-11eb-8980-064ac6cfcb2d.jpg) | ![2021-05-05_icon_text_space_3dp_center](https://user-images.githubusercontent.com/4698531/117173817-6f2c3080-adcd-11eb-8ea6-8d0307ff0116.jpg) | ![2021-05-05_icon_text_space_0dp_center](https://user-images.githubusercontent.com/4698531/117173838-72272100-adcd-11eb-808f-b36ee2bb6af4.jpg)

For screenshots 4, 5 and 6, it is the same than above except that the text is aligned to top instead of aligned center.

| 4/ Align top + Current space | 5/ Align top + Smaller space | 6/ Align top + No space |
| --- | --- | --- |
| ![2021-05-05_icon_text_space_5dp_top](https://user-images.githubusercontent.com/4698531/117174432-00030c00-adce-11eb-90af-8bb917655193.jpg) | ![2021-05-05_icon_text_space_3dp_top](https://user-images.githubusercontent.com/4698531/117174443-02656600-adce-11eb-9be4-c4771e32b152.jpg) | ![2021-05-05_icon_text_space_0dp_top](https://user-images.githubusercontent.com/4698531/117174455-04c7c000-adce-11eb-87be-527ce3875ae6.jpg) |

---

> **xi7**: also add visual feedback when click apps

=> What visual feedback do you have in mind?
For me, the app opening when you click on it is enough as a visual feedback...

Best regards.

**Comment by ycbmwig3338** [comment]
Actually, when it comes to matters of the heart, I think games should be down to 0. Whereas courtship may involve a short series of tests, love is not ultimately a feeling or even a win state but rather a consensual choice to commit.

**Comment by xi7** [comment]
number 6

**Comment by AeOeAa** [comment]
4 or 5

**Comment by xi7** [comment]
https://user-images.githubusercontent.com/67331785/117288124-8ad11e80-ae41-11eb-8134-b9bdf8fda58c.mp4

with visual feedback and w/o visual feedback discreet launcher v3.2.0

**Comment by falzonv** [comment]
Thank you for your votes!
I see that everyone is agree about text alignment on top :-)

Regarding the spacing:
- @xi7 prefers screenshot 6 (no padding)
- @AeOeAa prefers screenshot 4 (current padding) or 5 (smaller padding)
- Seeing them side to side, I personally find screenshot 5 (smaller padding) more elegant

=> In release v3.4.0, I will change the current spacing and alignment to match screenshot 5.

---

Ok for visual feedback @xi7, now I see what you mean.
This will be followed in ticket #38.

Best regards.

**Comment by falzonv** [comment]
Hello,

I am pleased to inform you that new release v3.4.0 has been published!

Here are the usual availability delays for each location:
- 4 to 8 days on F-Droid
- 0 to 2 days on Google Play
- Already available as direct APK on GitHub (https://github.com/falzonv/discreet-launcher/releases)

*Remarks:
I will leave this ticket opened until the release is effectively published on F-Droid.
You can use the export/import feature to switch from one version to another.*

Best regards.

**Comment by falzonv** [comment]
Since yesterday v3.4.0 is now available on F-Droid so I will close this ticket.
