### ISSUE TITLE
overview solution

### ISSUE THREAD

**Issue by xi7** [falzonv/discreet-launcher#312]
add option 'overview' if no labels, scroll apps gridview is unnecessary and slow solution without names.

https://play.google.com/store/apps/details?id=com.rcmz.chromalauncher

**Comment by falzonv** [comment]
Hello,

Thank you for the suggestion but no more new features or options will be implemented in Discreet Launcher. Only maintenance releases to fix bugs and maintain compatibility with new Android versions will continue.
You can find more details in ticket [#314](https://github.com/falzonv/discreet-launcher/issues/314).  

Best regards.
