### ISSUE TITLE
feature request: Fuzzy searching 

### ISSUE THREAD

**Issue by vnckppl** [falzonv/discreet-launcher#315]
It would be nice having fuzzy search enabled in the search menu. Now, when you have an app named F-droid and you search for droid, the F-droid app is not found.

**Comment by falzonv** [comment]
Hello,

Thank you for the suggestion.

It was indeed the original approach to search at any position of the app name, but quite often there were too many irrelevant results and this made the feature to launch the first search result with Enter difficult to use in practice.
Now the search looks only from the beginning of the app name which make it easier to get the desired app first in the list, and is also simpler and more efficient from code perspective. I do not plan to come back to the original approach.

However, I should mention that Discreet Launcher allows to rename apps (by long-pressing their icons and choosing "Rename") which in turn will affect the search results (and the app position in the app drawer).
So, to stay with the F-Droid example, if you renamed "F-Droid" to "Droid" you could find it when searching "droid".
This can be useful when some app names start with small words such as "A Time Tracker", it could be renamed in "Time Tracker".
*Note: this of course will only affect the display in Discreet Launcher, the real name of the app is not (and cannot) be modified.*

Best regards.
