### ISSUE TITLE
Change Tap Detection for Interactive Clock

### ISSUE THREAD

**Issue by AdalynBlack** [falzonv/discreet-launcher#324]
I'd love to have the interactive clock enabled, but I constantly tap it when swiping to access the trays. If it were possible to make it only check to open on release, and to take into account the movement speed of the finger when doing so to filter out quick movements from a static tap, that would greatly reduce the number of false positives, and make it more intuitive to use

**Comment by falzonv** [comment]
Hello,

Sorry for the late reply and thank you for the report!

I am not sure taking into account the speed will be possible due to how the clock view is designed, but making it open only on release might be feasible and enough to improve the situation.
When I have some time I will have a look at it.

Best regards

**Comment by falzonv** [comment]
Hello,

I was able to improve the behavior:
- Before, the app was started immediately after the interactive clock was touched.
- Now, both the initial touch and its release need to happen in the interactive clock for the app to be started which should prevent most accidental launches (I wanted to handle only the release event but it is never received in the clock view if this view didn't handle the initial touch first, so I have to check both).

The new release v7.5.0 has been published few minutes ago.
Here are the usual availability delays for each location:
- 4 to 8 days on F-Droid
- 0 to 2 days on Google Play
- Already available as direct APK on GitHub (https://github.com/falzonv/discreet-launcher/releases)

*Remarks:
I will leave this ticket opened until the release is effectively published on F-Droid.
You can use the export/import feature to switch from one version to another.*

Best regards.

**Comment by AdalynBlack** [comment]
Nice! Thanks for taking the time to implement that
I've had the interactive clock turned off for a long time as a result of this bug, but I'd love to be able to turn it on once the update is available on F-Droid

**Comment by Zybque** [comment]
It does the trick for me too. Thanks a lot!

**Comment by falzonv** [comment]
Great, thank you for the feedback!
