### ISSUE TITLE
Can you add some transitions And can I edit favorites??

### ISSUE THREAD

**Issue by velade** [falzonv/discreet-launcher#325]
This is the simplest desktop I've found, but simple doesn't always mean shabby, It would also be nice to at least add a 2D sliding transition when calling out the app list and favorites.And I didn't find a way to edit the sorting of favorites, which made me have to add them in order when adding them, and then when I wanted to replace other content inside, I couldn't place them in the usual position.Compared with simplicity, it now feels more crude to me. There are not even the most basic animations and functions. Advanced simplicity should be simple but gorgeous at the same time. It can look like there are very few things, but every detail is worthy of praise, even amazing. Instead of looking like nothing, simplicity never conflicts with magnificence, but the combination of simplicity and simplification often makes it look more simplistic, not concise.
My English is not good, so I used a translator to translate this post. If the words used are offensive, please understand in a friendly direction.

**Comment by Zybque** [comment]
Hello Velade,

You can sort favourites in the menu. Hit "⭐ favourites" and move apps up/down with 🔼/🔽

The app is not being developed anymore. So if you want a slider you have to fork it and make it yourself.

I am just a user but I think animations are not necessary. 

The app will get maintained so if you are, like me, happy with what it is you can still safely use it.

What language do you use? Translate this status for more information:
https://github.com/falzonv/discreet-launcher/issues/314#issue-1837111224

Take care!
Sipke

**Comment by falzonv** [comment]
Hello,

Thank you @Zybque for the great answer, I couldn't have said better, and I am glad you like the launcher :-)

For information, in the favourites menu you can also directly drag-and-drop apps vertically, the arrows were added later to improve accessibility for blind users (more details in https://github.com/falzonv/discreet-launcher/issues/211#issuecomment-1251399351).

@velade:
I will close this ticket as a duplicate from #101 where I explained the reason for the absence of animations:
> - One of the goals I try to keep with this launcher is to provide instant access to favorites or app drawer with one gesture (which can even be very small, the "trigger limit" for the swipe is quite low).
>    - Adding an animation (ex: roll or slide) would automatically delay the access to apps by the length of the animation. Even if it only adds 100-200ms, this delay is something that always frustrated me in other launchers I used before.

Best regards
