### ISSUE TITLE
Quickly uninstall by hold down on the App icon

### ISSUE THREAD

**Issue by lesar8** [falzonv/discreet-launcher#327]
Hello, when I want to uninstall an app it takes quite a lot of time to navigate to Settings > Apps section. It would be so nice if Discreet launcher add an "Uninstall" option to the context menu by hold down on the App icon.

I also suggest to remove the "Open.." option in the context menu because it's just faster to touch the icon itself to run an App :-)

I hope you can consider this idea and perhaps implement it in a future update. Thank you!

**Comment by falzonv** [comment]
Hello,

Thank you for the suggestions!

As I explained in ticket #140, I am not really in favor of a direct "Uninstall" option.
There is already the context menu option "Access its settings" to directly open the settings page for the targeted app, where the Android's Uninstall button is located.

The "Open..." option is indeed somewhat redundant, but it may be useful in case the user wants to open the app but ends up pressing its icon longer than expected (for example, disturbed by talking to someone), it avoids having to close the menu to click the app again.

Best regards.
