### ISSUE TITLE
crashes when I try to set a custom icon pack

### ISSUE THREAD

**Issue by nathgit** [falzonv/discreet-launcher#329]
This works fine until I try to set an icon pack. It crashes & goea to the system launcherthw only way to fix it, is to open the launcher's "app info* screen & clear data, then press open. I'll include the contents of the launcher backup in a comment.

I have a moto gplay 2021, running Android 11.

**Comment by nathgit** [comment]
# Export Discreet Launcher v7.5.0 (May 16, 2024 3:43:08 AM)
# Editing this file may cause problems
#
# Content of internal text files
favorites.txt: {com.wb.clipboard.pro/clipto.AppContainer}
favorites.txt: {com.duckduckgo.mobile.android/com.duckduckgo.app.launch.LauncherBlack}
favorites.txt: {org.fdroid.fdroid/org.fdroid.fdroid.views.main.MainActivity}
favorites.txt: {nextapp.fx/nextapp.fx.ui.ExplorerActivity}
favorites.txt: {com.habitrpg.android.habitica/com.habitrpg.android.habitica.ui.activities.MainActivity}
favorites.txt: {com.chimbori.hermitcrab/com.chimbori.hermitcrab.AdminActivity}
favorites.txt: {com.motorola.messaging/com.android.messaging.ui.conversationlist.ConversationListActivity}
favorites.txt: {com.android.dialer/com.android.dialer.main.impl.MainActivity}
favorites.txt: {com.android.vending/com.android.vending.AssetBrowserActivity}
folder_stores.txt: {org.chromium.webapk.aba26e7e4b34c5bca_v2/org.chromium.webapk.shell_apk.h2o.H2OOpaqueMainActivity}
folder_stores.txt: {org.fdroid.fdroid/org.fdroid.fdroid.views.main.MainActivity}
folder_stores.txt: {org.chromium.webapk.a2280d771eb1faeda_v2/org.chromium.webapk.shell_apk.h2o.H2OOpaqueMainActivity}
folder_stores.txt: {com.android.vending/com.android.vending.AssetBrowserActivity}
folder_stores.txt: {org.chromium.webapk.a51dcf9a547dd3b3b_v2/org.chromium.webapk.shell_apk.h2o.H2OOpaqueMainActivity}
folders_colors.txt: none
hidden.txt: none
rename_apps.txt: none
shortcuts.txt: none
shortcuts_legacy.txt: none
#
# Settings
application_theme: none
transparent_status_bar: true
dark_status_bar_icons: false
icon_size: 4
hide_app_names: false
hide_folder_names: false
remove_padding: false
background_color_favorites: #66000000
text_color_favorites: #FFFFFFFF
background_color_drawer: #66000000
text_color_drawer: #FFFFFFFF
clock_format: h:mm a
clock_color: #FFFFFFFF
clock_shadow_color: #66000000
clock_position: top
clock_size: medium
icon_pack: none
icon_pack_secondary: none
icon_color_filter: #00000000
notification: false
forced_orientation: none
always_show_favorites: false
reverse_interface: false
immersive_mode: false
touch_targets: false
interactive_clock: true
clock_app: {com.google.android.deskclock/com.android.deskclock.DeskClock}
hide_menu_button: false
disable_app_drawer: false
double_tap: {discreetlauncher.search/discreetlauncher.search}
swipe_leftwards: none
swipe_rightwards: {discreetlauncher.search/discreetlauncher.search}
#
# Saved icons
#

**Comment by nathgit** [comment]
I didn't change anything, but it seems to have fixed itself. It appears to be staying set as default. As long as I don't try to change set an icon pack

**Comment by falzonv** [comment]
Hello,

Thank you for the bug report, I am not sure what is happening because I just tested switching with 3 different icon packs and all of them worked fine.
Which icon pack are you trying to set?
Maybe this is an issue with this particular icon pack...

Best regards
