### ISSUE TITLE
won't stay set as default launcher

### ISSUE THREAD

**Issue by nathgit** [falzonv/discreet-launcher#330]
I set this as the default launcher, but every time I switch to an app, when I go back to home, it opens the system launcher, & I have to reopen discreet. when I reopen an app again, & closes it, it again goes back to the system launcher. what's the problem? Launcher backup is in the next comment.

I have amoto gplay 2021, running Android 11.

**Comment by nathgit** [comment]
# Export Discreet Launcher v7.5.0 (May 16, 2024 3:43:08 AM)
# Editing this file may cause problems
#
# Content of internal text files
favorites.txt: {com.wb.clipboard.pro/clipto.AppContainer}
favorites.txt: {com.duckduckgo.mobile.android/com.duckduckgo.app.launch.LauncherBlack}
favorites.txt: {org.fdroid.fdroid/org.fdroid.fdroid.views.main.MainActivity}
favorites.txt: {nextapp.fx/nextapp.fx.ui.ExplorerActivity}
favorites.txt: {com.habitrpg.android.habitica/com.habitrpg.android.habitica.ui.activities.MainActivity}
favorites.txt: {com.chimbori.hermitcrab/com.chimbori.hermitcrab.AdminActivity}
favorites.txt: {com.motorola.messaging/com.android.messaging.ui.conversationlist.ConversationListActivity}
favorites.txt: {com.android.dialer/com.android.dialer.main.impl.MainActivity}
favorites.txt: {com.android.vending/com.android.vending.AssetBrowserActivity}
folder_stores.txt: {org.chromium.webapk.aba26e7e4b34c5bca_v2/org.chromium.webapk.shell_apk.h2o.H2OOpaqueMainActivity}
folder_stores.txt: {org.fdroid.fdroid/org.fdroid.fdroid.views.main.MainActivity}
folder_stores.txt: {org.chromium.webapk.a2280d771eb1faeda_v2/org.chromium.webapk.shell_apk.h2o.H2OOpaqueMainActivity}
folder_stores.txt: {com.android.vending/com.android.vending.AssetBrowserActivity}
folder_stores.txt: {org.chromium.webapk.a51dcf9a547dd3b3b_v2/org.chromium.webapk.shell_apk.h2o.H2OOpaqueMainActivity}
folders_colors.txt: none
hidden.txt: none
rename_apps.txt: none
shortcuts.txt: none
shortcuts_legacy.txt: none
#
# Settings
application_theme: none
transparent_status_bar: true
dark_status_bar_icons: false
icon_size: 4
hide_app_names: false
hide_folder_names: false
remove_padding: false
background_color_favorites: #66000000
text_color_favorites: #FFFFFFFF
background_color_drawer: #66000000
text_color_drawer: #FFFFFFFF
clock_format: h:mm a
clock_color: #FFFFFFFF
clock_shadow_color: #66000000
clock_position: top
clock_size: medium
icon_pack: none
icon_pack_secondary: none
icon_color_filter: #00000000
notification: false
forced_orientation: none
always_show_favorites: false
reverse_interface: false
immersive_mode: false
touch_targets: false
interactive_clock: true
clock_app: {com.google.android.deskclock/com.android.deskclock.DeskClock}
hide_menu_button: false
disable_app_drawer: false
double_tap: {discreetlauncher.search/discreetlauncher.search}
swipe_leftwards: none
swipe_rightwards: {discreetlauncher.search/discreetlauncher.search}
#
# Saved icons
#

**Comment by nathgit** [comment]
I didn't change anything, but it seems to have fixed itself. It appears to be staying set as default. As long as I don't try to change set an icon pack. #329

**Comment by falzonv** [comment]
Yeah, I don't know why you are having this crash with the icon pack but when a launcher crashes too often, Android 11 removes it from being the default launcher.
