### ISSUE TITLE
How do folders in icon packs work exactly?

### ISSUE THREAD

**Issue by Zybque** [falzonv/discreet-launcher#331]
Maybe I'm doing something wrong but I don't understand how to make it so my folders get appropriate folder icons from a folder pack (arcticons in my case)

Or maybe I just misunderstood that this is possible now. I hope @kaanelloed or @Donnnno find time to enlighten me.

I tried creating folders with folder names appearing in arcticons. Like "Folder Phone" or jest "Phone" but they keep appearing as the default discreet-home-arrow. So it probably doesn't work that way. But how does it work?

It's not of vital importance. It's just frustrating to know it's possible but I don't know how 😁

**Comment by kaanelloed** [comment]
Have you installed the latest version of Arcticons and Discreet Launcher?

**Comment by Zybque** [comment]
Via /e/os app lounge:
Discreet: 7.5.0
Arcticons 8.7.1
So I updated arcticons to 9.2.4 and now it works!
Or anyway: it displays a folder icon and the amount of apps in it. Which is probably what it is supposed to show. I hoped it to pick "Folder Phone" or "games" as specific folder items but I'm content with this 😃

Thanks for pointing out the obvious @Donnnno, sorry I disturbed you with my n00bness.

**Comment by kaanelloed** [comment]
Yes, it's supposed to display a folder icon with the number of apps
