### ISSUE TITLE
Clock unreadable when switching dark/light

### ISSUE THREAD

**Issue by tasmo** [falzonv/discreet-launcher#332]
The color switch from #52 works perfectly.

My phone also switches the wallpaper light at day and dark at night.
But then the clock becomes unreadable.

It would very great to either switching the clock's color from system or depending on wallpaper.

**Comment by falzonv** [comment]
Hello,

Thank you for the suggestion but no more new features or options will be implemented in Discreet Launcher. Only maintenance releases to fix bugs and maintain compatibility with new Android versions will continue.
You can find more details in ticket [#314](https://github.com/falzonv/discreet-launcher/issues/314).  

By default the text clock is white with a black shadow and, thanks to this combination, should be readable on most wallpapers. The text and shadow colors can also be adjusted in the "Appearance" menu if needed.

Unfortunately for the analog clock I never managed to properly display a shadow (when I tried, shadows from the large circle, the ticks and the hands overlapped in a disgraceful manner) so this one may indeed look bad on some wallpapers.
However you can still adjust its color to try making it work with your wallpapers (the clock can support any RGB color so probably some should work, maybe a light blue or gray).

Best regards.
