### ISSUE TITLE
clock: Display home time zone as well as local zime zone

### ISSUE THREAD

**Issue by joriscode** [falzonv/discreet-launcher#333]
**Context**
When traveling, it is convenient to keep track on home time zone while also having local time zone available. My preference is to set automatically main clock on local time zone and have a secondary clock set manually on my home time zone. This allows me to be aligned with the place I'm at the moment while also being aware of home time for meeting and personal calls.

**Suggestion**
Allow a second clock on main & lock screens.

**Discussion**
- Clock app has a `Home time zone` settings with possibility to display it. Within the app, I can see my local time on top and home time beneath (and below other selected time zones). I imagine this information could be used by the launcher.
- To enable it, I think the settings from the Clock app could be re-used (if accessible) and additional parameters on the launcher appearance could be applied.
- About the layout, the simpler the better: a top left main clock and a smaller on the right home clock. I imagine format as time and date. Only main clock would be displayed if there is no time difference between the two clocks (and therefore, the usually display settings could be applied: position, format, ...).
- I would limit the functionality to main and local clocks, discarding the possibility to display custom time zone.

Thank you for considering this feature. I tried to give an idea of what it could look like and I'm aware this is a more complex feature that it sounds at first!

**Comment by falzonv** [comment]
Hello,

Thank you for the suggestion and very well formatted requested, however no more new features or options will be implemented in Discreet Launcher.
Only maintenance releases to fix bugs and maintain compatibility with new Android versions will continue.
You can find more details in ticket [#314](https://github.com/falzonv/discreet-launcher/issues/314).  

To answer some points of the discussion part:
- As far as I know, non-system apps cannot do anything about the lock screen.
- Discreet Launcher cannot access settings or data from other apps, it can access the system clock but I am not even sure if it can check if its timezone is configured to be adjusted automatically (would always be local timezone) or not (would always be home timezone).
- I don't think the layout part would be easy to handle, it's [already quite complex right now](https://github.com/falzonv/discreet-launcher/blob/main/app/src/main/java/com/vincent_falzon/discreetlauncher/ViewClock.java#L138-L347). The user may also use the analog clock format so a different integration would be needed for that.

If the Clock app handles that well, I would suggest setting it as a favorite when you are traveling (you can do this by long-pressing the app icon and clicking "Add to favorites", same process to remove).

Best regards.
