### ISSUE TITLE
Feature request: no labels just for favorites

### ISSUE THREAD

**Issue by ceving** [falzonv/discreet-launcher#334]
It is possible to hide the labels. This is fine for favorites, but difficult for the full list of apps, because the full list contains apps, which are used rarely.

I would like to be able to hide the labels for favorites but show the labels for the full app list.

**Comment by falzonv** [comment]
Hello,

Thank you for the suggestion but no more new features or options will be implemented in Discreet Launcher. Only maintenance releases to fix bugs and maintain compatibility with new Android versions will continue.
You can find more details in ticket [#314](https://github.com/falzonv/discreet-launcher/issues/314).  

As a workaround you may try to rename the favorites with just a space (long press an app icon to see the rename option), putting an empty new name will restore the original app name if needed.

Best regards.
