### ISSUE TITLE
Clarify some things in the Help (folders behavior, list update)

### ISSUE THREAD

**Issue by falzonv** [falzonv/discreet-launcher#34]
This ticket is created following @AeOeAa feedback in ticket #22:

> First impression is that there are some things that it took some trialling to figure out. Would it be possible to have the same app in different folders (no). Would it be possible to have in favourites both a folder with AppX in it and AppX (yes). Maybe write it in the help section?

---

=> Good idea, I will add explanations to clarify this in the Help section.
Not sure if many people would read them but at least it would exist somewhere in the application.

*Note: being quite busy currently, I will probably not start to work on this before next week*

**Comment by falzonv** [comment]
From discussion in ticket #25:

> There should always be a message "Applications list refreshed" displayed for a few moments each time the applications list is refreshed (no refresh happens without this message being displayed because it is included at the end of the process).
=> Maybe this is something that should be clarified in the Help section?

**Comment by falzonv** [comment]
Hello,

For information, this will be improved in the next release v3.3.0 which should be published during this week (not ready yet, and I would like to integrate some things from other tickets in the same release).

*Note: I will let this ticket opened until this release v3.3.0 is effectively published.*

Best regards.

**Comment by AeOeAa** [comment]
Perfect 👌

**Comment by falzonv** [comment]
Since v3.3.0 is finally available on F-Droid, I will close this ticket.
