### ISSUE TITLE
Find some way to make folders icons more distinguishable

### ISSUE THREAD

**Issue by falzonv** [falzonv/discreet-launcher#35]
This ticket is created following @AeOeAa feedback in ticket #22:

> The uniform folder icons do look sleek in favourites :grinning:
I would like to have some way of making the folder icons distinguishable. My workaround is using smileys in the beginning of the folder label as metaphors for the subject of the folders: :newspaper: :iphone: :video_game: :notes: :film_projector: :dollar: :joystick: :lock: :vibration_mode: :books: :medical_symbol: :e-mail: :mega:

---

=> You are right, it would be good to allow for custom icons. The problem is that the proposed icons must come from somewhere (the uniform folders icon is embedded with the launcher). It could be taken from the installed applications icons but it may create confusion if the same icon is used both for an application and a folder.

I find your workaround awesome!
=> Now I wonder if this can be an idea for the folder icon selection: the user would choose any of the smileys on his/her phone, and this smiley would be converted in a folder icon (no idea yet if this is possible, it may look completely blurry if we only have access to the small version of the smiley).

*Note: being quite busy currently, I will probably not start to work on this before next week*

**Comment by falzonv** [comment]
Hello @AeOeAa,

Status update!

After many tests, it seems that I will not be able to implement the idea mentioned above with an "emoji selector".
Trying to recognize the first character as an emoji to transform it in a folder icon is also not working well :-/ *(before even trying to transform an emoji in icon, there are several troubles to reliably recognize and get the emoji code itself...)*

---

Fortunately, I was able to make something different works and it may be a quite acceptable solution :-)

I do not want to package additional icons with the launcher (would unnecessarily increase the APK size).
However, being a launcher, we already have access to a large list of icons: the icons from applications themselves!

After several tests, I am able to add a folder setting allowing to choose an application from the complete list and use its icon for the folder instead of the default icon (the same setting allows to restore the default icon if wanted). The folder name and number of elements would avoid confusion between the folder and the application from which the icon was taken (and also, folders will be on top of the list starting with v3.3.0).

These are not dedicated icons for folders, but the selection is still probably large enough to solve the issue, especially for people who have many applications to choose icons from ;-)

Do you think it could work for you?

Best regards.

**Comment by AeOeAa** [comment]
Please see https://github.com/falzonv/discreet-launcher/issues/26#issuecomment-830757337

**Comment by falzonv** [comment]
Hello @xi7,

> I don't see the reason to increase the application with icons

=> With the solution of reusing icons of already installed applications (instead of embedding new icons in the launcher), the launcher size would not change.

> what about change the color folder ?

=> Good idea, this could also solve the issue!
Never tried to display a color picker in Android but this is certainly possible ;-)

@AeOeAa:
I think it is not necessary to implement both solutions at the same time.
What is you preference between these two options?
1. Allow to assign for a folder the same icon than any application installed on the phone
2. Keep the current folder icon but allow to change the color

Best regards.

**Comment by AeOeAa** [comment]
@falzonv

I think I agree with your point about package/app size, though I don't know if there's a lot of bytes in vector icons, fx?

Sorry, I don't know how I think about your suggested solution, I can't imagine how it will work implemented.

But I was just now thinking about how the option to use external icon packs might be an alternative solution for folder icons? (I don't know if there are any folder icon packs and how they would work, just thinking aloud)

Then the user could decide if he or she
* need folders + 
* need label-less shortcuts
* = need distinctive folder icons

**Comment by AeOeAa** [comment]
Oh we wrote in parallel.

I don't get the colour suggestion, it's related to "not increasing the application", not the use case.

**Comment by falzonv** [comment]
You are right that using vector icons would not increase much the application size if they are optimized (software generating vector images often add a lot of overhead).

But this leads to another problem: where to find open source optimized icons and how many would be needed? (personally I am not a very good drawer so I won't be able to do them myself)

---

For the solution I suggested, here is an example below where the icon of "Gallery" application has been selected for the folder.
Of course it shows the same icon as the real application, but it is on top of the list (as per ticket #32), has the folder name and shows the number of included elements.

![2021-05-06_folder_icon](https://user-images.githubusercontent.com/4698531/117331275-e37ed680-ae96-11eb-99e6-03ed4c113b3a.jpg)

---

The color suggestion is to allow the user to change the color of the folder icon. All folders would use the current icon but instead of being white (would stay the default), the user could customize the color of the lines.
*Note: nothing tested about it yet, it may be quite complicated to change the icon color since it is defined in the vector file itself.*

---

Regarding external icon pack, I would prefer a solution that do not require the user to install another application.
No idea either if this sort of packs exist for folders, probably not as they usually target applications...

**Comment by xi7** [comment]
folder contains names, it was supposed to be enough the current format, i think icons will increase cache/memory.

**Comment by xi7** [comment]
I'm waiting for the fdroid publish v3.3.0 , possible upload temporarily 3.3.0 ?

tell me about:

-need swipe sometimes ?
-others apps may can override the priority on the bar ?
-after many notifications, can it be difficult to find list?
-transparent bar ?

after the favorites follow users, would there be a need to keep the old favorite homescreen?

-old homescreen = yes
-by notification v3.2.0 = yes
- float can be high efficent many scenarios, 1click shows in any situation.

**Comment by AeOeAa** [comment]
@xi7 Folders doesn't contain names, when #26 is turned on. I suggested a change to #26 which is perhaps better than fixing this one (35). 

> (personally I am not a very good drawer so I won't be able to do them myself)

Me too.

> has the folder name and shows the number of included elements.

Not if #26 is turned on which kind of started this.

> ![2021-05-06_folder_icon](https://user-images.githubusercontent.com/4698531/117331275-e37ed680-ae96-11eb-99e6-03ed4c113b3a.jpg)

It looks fine, but I think making changes to #26 as I just suggested is perhaps a better soloutiion

> Regarding external icon pack, I would prefer a solution that do not require the user to install another application.
> No idea either if this sort of packs exist for folders, probably not as they usually target applications...

Well, the option to include icon pack is implemented and requires the user install another application?
But I agree that there's probably not an easy fix to "folder icon packs".

**Comment by xi7** [comment]
folder no need hide name, just apps.

**Comment by falzonv** [comment]
Hello @AeOeAa,

Thank you for your suggestion, I agree this is a better solution and have reopened #26 for follow-up.
I will close this ticket but feel free to add comments if needed.

---

> Well, the option to include icon pack is implemented and requires the user install another application?
But I agree that there's probably not an easy fix to "folder icon packs".

=> The behavior and expectation would be quite different actually.

Icon packs for applications contains many icons and a reference file named "appfilter.xml" telling which icon is for which application. When the user selects an icon pack with the setting, the launcher checks for each installed application if it has an icon in the pack to use it instead of the native icon. There is no user action involved other than choosing the pack.
When the user have no icon packs, the native application icons are used and it is probably the case for most users.

For folders, we would want the user to pick an icon in the pack because only him/her knows what will be the folder content and which icon would be appropriate. Many users do not have icon packs or are not aware about them being third-party apps (see #15 for example), so they would not be able to set an icon while seeing disabled settings to do so. Of course this could be explained in the help, but many people also don't read the help :joy:

Best regards.
