### ISSUE TITLE
Immersive mode

### ISSUE THREAD

**Issue by KaiFujiro** [falzonv/discreet-launcher#36]
Hello
 Can you add the Immersive mode feature?
 with / without root.

 I searched a lot for a launcher like this and wished there was an immersive mode for android lollipop, but there wasn't.
 I hope you can add this feature

**Comment by ycbmwig3338** [comment]
I think if anything it is not immersive enough. Too ironic.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by AeOeAa** [comment]
@KaiFujiro What do you mean, immersive mode? You just want to hide navigation/system bars? Or is there some part of the immersive mode, you think the launcher would gain from?

It's possible to hide both the navigation bar and the status bar without calling immersive mode. Typically, the navigation will return with just a touch somewhere on the screen.

Personally, I don't want find to do something extra each time I want to interact with the navigation. Even if it's just a tap. Especially if I have to do a special gesture like edge swipe.

**Comment by falzonv** [comment]
Hello,

Thank you very much for your interest in this project!
It should be possible to add this mode, I will have a look and keep you updated.

---

Thank you very much @AeOeAa for this pre-analysis :-)

After checking [this page](https://developer.android.com/training/system-ui/immersive) from Android documentation, it seems there are in fact three fullscreen modes:
- **Lean back**: system bars are hidden and can be brought back with a tap anywhere on the screen, this is the mode often used by video players for example, it will not work in our case
- **Immersive**: this is what you were describing, system bars are hidden and can be brought back with swipes at their location (swipe down on top of the screen for status bar, swipe up from bottom for navigation)
=> This is the best choice in our case
- **Immersive sticky**: similar to immersive but the system bars are only partially brought back, this is for things like drawing applications where the user may need to swipe on an edge to draw, not really needed in our case

> Personally, I don't want to do something extra each time I want to interact with the navigation. Even if it's just a tap. Much worse if I have to do a special gesture like edge swipe.

=> Completely agree with you, this new "immersive mode" option will be off by default.

Best regards.

**Comment by ycbmwig3338** [comment]
Sighz

**Comment by ycbmwig3338** [comment]
When will you guys just come out and say it manz

**Comment by falzonv** [comment]
Hello @KaiFujiro,

I am pleased to inform you that this new feature will be implemented in v3.4.0 which should be published soon.

Best regards.

**Comment by drewski-00h** [comment]
I'm really digging the Immersive Mode added!  Is there a way to work around a phone with notch?  
![PXL_20210515_000627581 MP_2](https://user-images.githubusercontent.com/83047636/118342223-0d17ad80-b4e8-11eb-830a-b3f505fbb605.jpg)

**Comment by AeOeAa** [comment]
On my phone, the wallpaper is shown "under" the notch, the default in phone settings. However, in immersed mode, there is a black bar on top.

* this is what it looks like not immersed:
![Screenshot_20210515_105005_com vincent_falzon discreetlauncher](https://user-images.githubusercontent.com/13118178/118354511-adfb7c80-b56b-11eb-8af0-e9000705f7c1.jpg)

* this is what it looks like immersed
![Screenshot_20210515_105049_com vincent_falzon discreetlauncher](https://user-images.githubusercontent.com/13118178/118354560-e8651980-b56b-11eb-8e94-d76dfb0895ea.jpg)

The notch setting in phone settings:
![Screenshot_20210515_104923_com android settings](https://user-images.githubusercontent.com/13118178/118354689-9cff3b00-b56c-11eb-89c7-cf983b6fd254.jpg)

**Comment by falzonv** [comment]
Hello,

Thank you very much for your feedback!
Since I never had a phone with the notch this case was completely missed to be honest...
It can probably be improved to support notch better, I will have a look and keep you updated.

@AeOeAa: I am also a bit surprised that the navigation bar is translucent on your first screenshot, normally it should be fully transparent even with immersive mode disabled... Which Android version are you using?

Best regards.

**Comment by AeOeAa** [comment]
I'm at 10. Some Huawei UI.

Den søn. 16. maj 2021 kl. 20.50 skrev Vincent Falzon <
***@***.***>:

**Comment by falzonv** [comment]
Ok thank you I will have a look to this also (it may be something specific to Android 10 or 10+).

For information, this ticket will be closed (since immersive mode is implemented) and the discussion about notch support will continue in new ticket #50. I have already reported the conversation history there.
