### ISSUE TITLE
Add visual feedback when clicking application

### ISSUE THREAD

**Issue by falzonv** [falzonv/discreet-launcher#38]
This ticket is created following @xi7 suggestion in ticket #31:

> also add visual feedback when click apps
(+ video in ticket #31)

---

Thank you for the demonstration video :-)
Ok for me to add visual feedback, I will see how to do it and keep you updated.

Best regards.

**Comment by falzonv** [comment]
This will be implemented in v3.4.0 which should be published soon.

**Comment by falzonv** [comment]
Hello,

I am pleased to inform you that new release v3.4.0 has been published!

Here are the usual availability delays for each location:
- 4 to 8 days on F-Droid
- 0 to 2 days on Google Play
- Already available as direct APK on GitHub (https://github.com/falzonv/discreet-launcher/releases)

*Remarks:
I will leave this ticket opened until the release is effectively published on F-Droid.
You can use the export/import feature to switch from one version to another.*

Best regards.

**Comment by xi7** [comment]
try something more discreet like the video and not a target plz

https://user-images.githubusercontent.com/67331785/117691654-89ca2500-b192-11eb-9252-1746f0e55608.mp4

**Comment by falzonv** [comment]
Hum, ok I will have a look...

**Comment by falzonv** [comment]
Good news, it will be more discreet in the future release v3.6.0 :-)

**Comment by xi7** [comment]
working fine with 3.6.0, hold click, but i cant see with one click touch.

**Comment by falzonv** [comment]
Regarding single click, this is what I was mentioning above:

> Additional remark: visual feedback will be applied only on long click action, as displayed in your video.
I tried also on short click action but, as a new activity is started right after, the feedback is not even displayed.

This is what I tried when the user performs a single click:
- Add visual feedback
- Ask system to start clicked activity
- Remove visual feedback (or it will always stay on the app when coming back to the launcher)

But when doing this, the feedback is not visible (in reality it is added and immediately removed) because the waiting time after I sent the "start" instruction to the system happens outside of Discreet Launcher.

Since it was not visible, I decided to not apply visual feedback on single click.

After, I am also not sure to understand the use case for this.
For the long click it is clear, it allows to see better which app was clicked when the small "open/settings" popup appears.
But what is the interest for the short click? (since the clicked app will be started right after)

**Comment by xi7** [comment]
just not to be a dead screen, touch and show nothing

**Comment by xi7** [comment]
sometimes slow phone wait a long time to open the application and you don't know if it was clicked or not, a visual confirmation would be good in this case too

**Comment by falzonv** [comment]
Ok thank you for explanation.
I was able to find a solution and this will be added to the short click in the next release :-)

**Comment by falzonv** [comment]
Hello,

I am pleased to inform you that this has been solved in new release v4.0.0!
This release has been published a few minutes ago.

Here are the usual availability delays for each location:
- 4 to 8 days on F-Droid
- 0 to 2 days on Google Play
- Already available as direct APK on GitHub (https://github.com/falzonv/discreet-launcher/releases)

*Remarks:
I will leave this ticket opened until the release is effectively published on F-Droid.
You can use the export/import feature to switch from one version to another.*

Best regards.

**Comment by xi7** [comment]
working but i think have a better refined code, u using two blink touch 1 click and 1 long click, u dont need both

**Comment by falzonv** [comment]
In the code it is already using the same function for both clicks.

The only difference is the duration between enabling and disabling:
- For short click it is disabled after a 200ms delay
- For long click it is disabled when the popup menu is dismissed or an option is selected

**Comment by xi7** [comment]
a little difference last video, but working. tnks

**Comment by xi7** [comment]
what i see: 
- 1 click = 0ms
- when click and hold no show nothing until 200ms

**Comment by xi7** [comment]
https://user-images.githubusercontent.com/67331785/121096710-1b947480-c7c9-11eb-961a-29d58f0c8d3d.mp4

you forget when folder

**Comment by falzonv** [comment]
Hello,

> what i see:
> - 1 click = 0ms
> - when click and hold no show nothing until 200ms
>
> that what i mean, no need both

Yes, this is for enabling part.
To go a bit more in details, there are two functions:

- `OnClick()`: called after the user made a short click
  - The visual feedback is enabled at the start of this function, so it is displayed immediately as you noticed
  - It stays enabled for a duration of 200ms and then it is disabled
- `OnLongClick()`
  - Called after the delay Android needs to detect a long click
  - The visual feedback is enabled at the start of this function, but the function will be entered only after the delay Android considers as a long click (maybe 200ms, I have no idea and it probably vary a bit among devices)
  - It stays enabled until the user selects an option or dismiss the popup

In both cases the same `setVisualFeedback()` function is called, but I need both functions to provide different actions on short click and long click. They cannot be merged.

> you forget when folder

Actually the folder is done like any other application, but you are right the feedback is not visible on the icon because it is already white. I also tried with a gray visual feedback but I don't like how it looks.

This is why I applied a visual feedback also on the name instead of only the icon, if you try with "Games" you should see it on the name. Of course if the folder name is empty nothing is visible. But, even if it is not technically blocked (should it be?), folders are not supposed to have empty names so I will not manage this case.

Also, if I am able to make ticket #63 works and the user selects a custom folder color instead of the default white, the visual feedback will be visible also on the icon (and also with an empty folder name).

Best regards.

**Comment by xi7** [comment]
i dont understand too much english, but maybe you forget the visual feedback when icons inside folder. no show nothing, no 0s or 200s.

check the video app puffin both situation... app blink when home favorites and next test is into folder, no work.

**Comment by falzonv** [comment]
Oh ok, I understand now.
I thought you were talking about the visual feedback not visible enough on the folder itself, sorry.

What happens is that the folder is closed before the visual feedback is displayed (it is still applied, but the app is not visible anymore because the folder has been closed).
On long click, the visual feedback is visible because the folder is not closed.

Not sure if I can solve it without bringing back another bug: the reason to close the folder at this moment was to solve ticket #46.

**Comment by falzonv** [comment]
Since today release v4.0.1 is available on F-Droid so I will close this ticket.
Feel free to add comments if needed.

**Comment by xi7** [comment]
https://user-images.githubusercontent.com/67331785/140297297-ba74caca-7418-442a-ba82-856b1304afa5.mp4

plz, use effect pressed until open app.
