### ISSUE TITLE
Notification-favorites sometimes comes back to home screen

### ISSUE THREAD

**Issue by falzonv** [falzonv/discreet-launcher#39]
This ticket is created following @xi7 bug report in ticket #11:

> i cant use without auto back to home screen, it working appropriately ? android 5.0 close activity before choose apps

---

Previously in the same ticket, quoting myself:

> There is only one issue that I have to fix before this to be ready: sometimes the initial application is minimized and the favorites are displayed above the home screen. In this case, there is no direct return to the initial application :-/
>
> Most of the time it works as expected (favorites are displayed above the initial application) so the issue is not easy to reproduce or understand, but I would like to solve this before publishing the release.
>
> ---
>
> After further tries, the issue I observed may in fact be related to the development environment.
It does not seem to happen when using the application outside of debug mode, quite strange...
=> I will publish the release like this and we will see if other people are facing the issue.

---

Hello,

Interesting, this is the bug I was mentioning previously but which seemed to be only with my development setup.
Apparently not...

Here are a few questions to try to understand when it happens:
- Is Discreet Launcher your default launcher when you observe the bug?
- Is Discreet Launcher displayed in the recent apps list when you observe the bug?
  - If yes, do you still have the bug if you remove it from recent apps, click the Home button and try again?

Normally Discreet Launcher is excluded from recent apps (since it is the launcher), but it seems it can be there depending on how the application is started. I also have the impression that this bug is happening in those special cases.

Best regards.

**Comment by falzonv** [comment]
Ok, thank you for the test.
=> Do you also have the bug if you clear all apps (with the "clear all" button, to clear also possible hidden apps) and come back to home screen? *(when testing on my side it works, and after the problem does not reappear again)*

---

Since v3.3.0 is now available on F-Droid, **I tried to install it from F-Droid and everything works directly as excepted** (notification is properly displayed above applications). The same when testing upgrade from v3.2.0 to v3.3.0 using F-Droid versions.

**I suspect that this bug is only when Discreet Launcher is launched by something else than the system** (for example, launched by the debug environment that I use, or the file manager where you click on the APK, ...). It would be launched as a foreground process that would be brought back when displaying the favorites from notification (if launched by the system, it would stays in background and the window would open above apps).

This is still not sure, but the only explanation I see so far. If this is the case, since the issue happens before the launcher is even started, I will probably not be able to do much (except mention it in the help with the "clear all" solution).

@AeOeAa, @tuch96
If you already have v3.3.0 from F-Droid or v3.4.0 from APK, do you also observe this bug? If so, is the workaround of clearing all apps with the "clear all" button (needed only once) working?

**Comment by xi7** [comment]
https://user-images.githubusercontent.com/67331785/118016193-7ef6c800-b32b-11eb-99eb-80d9dedf57f9.mp4

here no work

**Comment by falzonv** [comment]
Then I have no other idea for now...
(Well, you could try v3.3.0 from F-Droid but that is again an uninstall/install operation)

Let's wait for other feedbacks, maybe that will give other ideas.

**Comment by xi7** [comment]
https://user-images.githubusercontent.com/67331785/118018136-cda56180-b32d-11eb-861a-a6f2c55d74a5.mp4

v.3.3.0 still same.

**Comment by falzonv** [comment]
> you could try v3.3.0 **from F-Droid**

**Comment by xi7** [comment]
after clear data/cache was pressed home button, fdroid 3.3.0

**Comment by AeOeAa** [comment]
> @AeOeAa, @tuch96
> If you already have v3.3.0 from F-Droid or v3.4.0 from APK, do you also observe this bug? If so, is the workaround of clearing all apps with the "clear all" button (needed only once) working?

I don't observe this and I haven't noticed it earlier either... I'm on 3.4 from apk here at github (installed after settings export and 3.3 via F-Droid removed, and settings imported).

I don't understand the steps to reproduce so I'm not able to test it either, I'm sorry.

**Comment by tuch96** [comment]
> > @AeOeAa, @tuch96
> > If you already have v3.3.0 from F-Droid or v3.4.0 from APK, do you also observe this bug? If so, is the workaround of clearing all apps with the "clear all" button (needed only once) working?
> 
> I don't observe this and I haven't noticed it earlier either... I'm on 3.4 from apk here at github (installed after settings export and 3.3 via F-Droid removed, and settings imported).
> 
> I don't understand the steps to reproduce so I'm not able to test it either, I'm sorry.

I installed the f-droid version 3.3 today. I can't observe that either. Everything works very well for me.

**Comment by falzonv** [comment]
Ok, thank you very much for your feedbacks!
This confirms that it can works fine from both F-Droid and the APK file, even without requiring any workaround.

---

When testing with an Android 5 emulator, I noticed there was no "clear all" button in the recent apps section :-/
That is why @xi7 was not able to apply the workaround which worked for me on Android 8.

And indeed, using the F-Droid version or "force stopping" the app does not solve it with Android 5.

I know it can work with Android 5 because this is what I used when creating the screenshot from [this comment](https://github.com/falzonv/discreet-launcher/issues/11#issuecomment-832079014) and the source code have not specially changed in between.
On the other hand, I was not yet able to reproduce the screenshot linked above :-/

**Comment by falzonv** [comment]
After other tries, I made some changes in the way the favorites popup is launched and, after a reboot, it should solve the issue for Android 5 (at least I am now able to make it work in my Android 5 emulator).

Still not sure why a reboot is needed, but in my tests it was working only after doing it (and not with v3.4.0, only after tweaks from v3.5.0 were implemented).

I have now published this in v3.5.0 so you can test it (best would be to try before and after smartphone reboot), I have also mentioned the workarounds in the help section.
=> In case this still doesn't work for you, I am sorry but it seems I will not be able to fix it :-/

As a reminder, here are the usual availability delays for each location:
- 4 to 8 days on F-Droid
- 0 to 2 days on Google Play
- Already available as direct APK on GitHub (https://github.com/falzonv/discreet-launcher/releases)

*Remarks:
I will leave this ticket opened until the release is effectively published on F-Droid.
You can use the export/import feature to switch from one version to another.*

**Comment by xi7** [comment]
3..5.0 working perfectly !

**Comment by falzonv** [comment]
Great, thank you for the confirmation!

**Comment by falzonv** [comment]
Since v3.5.0 is now available on F-Droid since yesterday, I will close this ticket.
