### ISSUE TITLE
Disable hardware acceleration to lower memory usage

### ISSUE THREAD

**Issue by falzonv** [falzonv/discreet-launcher#4]
*This ticket is created to cover the following point from ticket #3 opened by @xi7*

*"the app is very small but need a lot of waste memory load"*

---

Hello,

This might be due to the list of applications (more precisely their icons) which is kept in memory to avoid recomputing it each time we open the applications drawer or the favorites panel.

As a result, there is a high memory usage when building the applications list (for example icons have to be set at an uniform size) but it happens only on first start or when manually triggered with the refreshing button. Once this process is finished, the usage decreases to keep only the computed list in memory.

Checking on my Android 8.1 phone with ~60 applications, it seems the average memory use during the last three hours was 24 MB (that is, approximately 0.4 MB per application). It also mentions a maximum peak at 123 MB which most probably happened the last time the applications list was refreshed (it was yesterday).

There is probably room for improvement, I will think about it and keep you updated.

Best regards.

**Comment by xi7** [comment]
add AndroidManifest.xml <application> 
android:hardwareAccelerated="false"

you will considerably reduce the use of memory , app analyzed 3C task manager.

**Comment by falzonv** [comment]
Interesting, thank you for the tip!

I will have to do some tests with it to see what it does exactly (there is probably a reason for it to be "true" by default) but if there is no downsides I will indeed add it to the manifest.

**Comment by xi7** [comment]
improve ram and consequently the battery, but i think u can be better reducing your code.

**Comment by xi7** [comment]
https://user-images.githubusercontent.com/67331785/111193464-f3fe8900-8598-11eb-958c-9105b82c2dca.mp4

you can check this video test, 4 different launcher and discreet launcher without load any icon memory still using high ram

**Comment by falzonv** [comment]
Hello,

Thank you for this information, I have one remark to explain how the application works internally:

*"discreet launcher without load any icon, memory still using high ram"*
=> Even if there are no applications yet in the favorites panel, the complete applications list (and icons) has already been retrieved and stored in memory. This allows to immediately open the applications drawer if you swipe up from the home screen.
=> Consequence: the memory usage is almost the same with or without favorites applications selected.

---

After doing several tests with hardware acceleration disabled, I will not configure this for two reasons:

1. When looking at the Android Studio memory profiler there is almost no difference (in fact sometimes it was even better with hardware acceleration enabled...). I guess that for some applications it allows to lower the memory usage, but mine is not part of them apparently.
2. After disabling hardware acceleration, the navigation in the app (opening/closing the favorites panel and scrolling in the application drawer) became very slower and not smooth at all which is, in my opinion, a big regression for user experience.

I still made a complete review of the code and performed several small optimizations in release v1.2.0. It will probably not make a revolution about memory usage but it simplified some parts of the code.

---

For now I will not work on that memory part anymore.

Considering that it includes all installed applications and their icons, the memory usage is not so high. Of course it is higher than an application not keeping these data in memory, but this is a design choice to make the launcher as quick as possible while staying quite beautiful and user-friendly by showing icons.

To be honest, I am also using this application as my main launcher since 2019 (only published it on GitHub a month ago) and I have never faced any issue related to memory.

Best regards.
