### ISSUE TITLE
Show number of folder elements in the icon rather than name

### ISSUE THREAD

**Issue by falzonv** [falzonv/discreet-launcher#40]
This ticket is created following @xi7 suggestion in ticket #11:

> ![Screenshot_2021-05-07-09-37-27](https://user-images.githubusercontent.com/67331785/117452001-a3ad0300-af19-11eb-9986-7c7771a3fcea.png)
quantity into the house (update if u like)

> the gridview will only be useful when new apps have been installed, i will use everything in the favorites as shown last pic (all_apps), much more interesting the access by the notifications, fast and efficient. but it gets ugly disorganized :(
>
> ![Screenshot_2021-05-07-09-37-27](https://user-images.githubusercontent.com/67331785/117534392-977f7f00-afc7-11eb-95e9-ec3b54011d65.png)
> 
> 1 or 2 ? I think favorites look like number 1

---

Interesting idea!
Screenshot 1 looks better :-)

Not sure how to do it programmatically but I will have a look.

**Comment by drewski-00h** [comment]
That looks a lot better!

**Comment by falzonv** [comment]
Hello,

I am pleased to inform you that number of items in folder icon has been implemented in new release v3.5.0 which has been published few minutes ago!

Here are the usual availability delays for each location:
- 4 to 8 days on F-Droid
- 0 to 2 days on Google Play
- Already available as direct APK on GitHub (https://github.com/falzonv/discreet-launcher/releases)

*Remarks:
I will leave this ticket opened until the release is effectively published on F-Droid.
You can use the export/import feature to switch from one version to another.*

Best regards.

**Comment by xi7** [comment]
great !

**Comment by AeOeAa** [comment]
Great job!

I don't know the use case for number of apps in a folder, but this sure looks better than the earlier label 👍

**Comment by falzonv** [comment]
Thank you for your feedback!

Indeed @AeOeAa, and it will also solve something you were mentioning in another ticket:

> For me, it happens more frequently with folder names because of the design choice of adding " (#)" to all titles, where # is the number of apps in the folder. I shortened some titles because of this.

**Comment by falzonv** [comment]
Since v3.5.0 is now available on F-Droid since yesterday, I will close this ticket.
