### ISSUE TITLE
Folder opened from notification-favorites cut in some cases

### ISSUE THREAD

**Issue by falzonv** [falzonv/discreet-launcher#43]
This ticket is opened following bug report from @xi7 in ticket #11:

> bug drawer and window freeze
(+ video)

> 1 = no show all list item
2 = click out layout but open app
(+ video)

---

Hello,

After some tries, I was able to understand that this bug happens only when the opened folder is higher than the favorites popup.
In this case, the folder is only partially displayed: the lower part is hidden.

It is this invisible lower part which prevents the click outside to close the folder. If you try to click above the folder and the favorites popup, it should close the folder as expected.

Not sure yet how to solve this bug, it seems the first half of the folder is displayed with the favorites popup, but the second half is lost somewhere.
I will work on it and keep you updated.

Best regards.

**Comment by falzonv** [comment]
Hello,

I am pleased to inform you that this was solved in new release v3.5.0 which has been published few minutes ago!
The folder popup size, when opened from favorites, is now adapted to the favorites window size (to not be cut/hidden like before).

Here are the usual availability delays for each location:
- 4 to 8 days on F-Droid
- 0 to 2 days on Google Play
- Already available as direct APK on GitHub (https://github.com/falzonv/discreet-launcher/releases)

*Remarks:
I will leave this ticket opened until the release is effectively published on F-Droid.
You can use the export/import feature to switch from one version to another.*

Best regards.

**Comment by xi7** [comment]
perfect ^_-

**Comment by falzonv** [comment]
Since v3.5.0 is now available on F-Droid since yesterday, I will close this ticket.
