### ISSUE TITLE
Set max lines for apps text to not disorganize the layout

### ISSUE THREAD

**Issue by xi7** [falzonv/discreet-launcher#47]
![Screenshot_2021-05-13-09-39-24](https://user-images.githubusercontent.com/67331785/118127304-e5cdbd00-b3cf-11eb-8c19-153072303c47.png)
![Screenshot_2021-05-13-09-39-33](https://user-images.githubusercontent.com/67331785/118127308-e6feea00-b3cf-11eb-8db4-6b14f8c5277d.png)

**Comment by falzonv** [comment]
Not sure why a user would want to give such a long name to a folder...
But if (s)he really wants to do it, why would we restrict it?

There is no bug here, only a very long name that can easily be renamed in the folders organizer.

**Comment by xi7** [comment]
I showed that the names disorganize the layout  v3.5.0.

should be limited 1 or max 2 lines. but i dont understand why illimited

**Comment by xi7** [comment]
https://user-images.githubusercontent.com/67331785/118481839-4ddf1480-b6ea-11eb-8ae9-5a2735f4cd6d.mp4

**Comment by falzonv** [comment]
Thank you for the explanation, now I understand what you wanted to show.

After making some tries with various screen sizes, I think a limit of max 3 lines is a better compromise than 1 or 2.
=> The display of applications and folders names will be limited to 3 lines in future release v3.6.0.

**Comment by xi7** [comment]
v3.6.0 long name still disorganize the layout folder, the delete folder disappears from the layout

**Comment by falzonv** [comment]
Indeed sorry, I was still thinking about your 2 first screenshots when working on this and I missed the folder settings part.

The folder name in the settings will go to next line in the next release instead of pushing buttons outside.

**Comment by falzonv** [comment]
Since today release v4.0.1 is available on F-Droid so I will close this ticket.
Feel free to add comments if needed.
