### ISSUE TITLE
Option background transparency change in favorites menu

### ISSUE THREAD

**Issue by tuch96** [falzonv/discreet-launcher#49]
Hi Vincent,

what do you think about a option to make the background of the favorite menu to 100% transparent? This new option make the favorite menu more cleaner. Maybe including a additional function to change the transparency effect from 0 to 100%. This could be perfect to find the correct usability arrangement between icon pack and background picture.

Kind regards!

**Comment by xi7** [comment]
and also grid_view and notification bar.

**Comment by falzonv** [comment]
Hello,

Thank you for the suggestion, yes it should be possible :-)
I will have a look and keep you updated.

Best regards.

**Comment by falzonv** [comment]
Hello,

For information, I am working on going even a step further by allowing the user to choose both the color and transparency level of the interface elements (it will be a unique setting applied to favorites background, drawer background and status bar).

Best regards.

**Comment by tuch96** [comment]
That sounds perfect. It could be a problem with the colour part because this is sometimes an internal system setting.

**Comment by falzonv** [comment]
Hello,

I am pleased to inform you that the custom background color has been implemented in new release v4.0.0!
This release has been published a few minutes ago.

Here are the usual availability delays for each location:
- 4 to 8 days on F-Droid
- 0 to 2 days on Google Play
- Already available as direct APK on GitHub (https://github.com/falzonv/discreet-launcher/releases)

*Remarks:
I will leave this ticket opened until the release is effectively published on F-Droid.
You can use the export/import feature to switch from one version to another.*

Best regards.

**Comment by tuch96** [comment]
Hi Vincent,

today I have installed the new version 4.0.1 from f-droid. The new functions are brilliant and works perfectly - no problems on my Lineage 17.1. The new sort function and the colour options brings an perfect minimalistic usability. Good job! Are you ready for some more ideas :-)?

Cheers!

**Comment by falzonv** [comment]
Hello,

Thank you very much for your feedback, I am glad you like the new release!

> Are you ready for some more ideas :-)?

Sure, feel free to create new tickets for them! :-)
*(I will close this one since v4.0.1 is now published)*

Best regards.
