### ISSUE TITLE
Offer setting to make the notification bar fully transparent

### ISSUE THREAD

**Issue by falzonv** [falzonv/discreet-launcher#5]
*This ticket is created to cover the following point from ticket #3 opened by @xi7*

*"add bar translucent notification"*

---

Hello,

The notification bar should already be translucent (see screenshots in the README.md).
On the Android versions 5.0, 8.1 and 11 that I am using to test, it is working as expected.

Which Android version are you using? Maybe this one is a special case...

Best regards.

**Comment by xi7** [comment]
https://user-images.githubusercontent.com/67331785/111184614-e1cc1d00-858f-11eb-9bf2-035c32d834ee.mp4

android 5, check translucent bar notification video. i dont speak good english but you will understand what i mean

**Comment by falzonv** [comment]
Oh ok, there was a misunderstanding then.
*(no problem, english is not my native language either, I am French)*

For me "translucent" means that there is a background but we can see through it (as in the screenshots) and "transparent" would be no background at all (as in your video). I was thinking you were having an issue with the notification bar not being "translucent" but in fact it is a feature request to have it fully "transparent".

There should be no issue to add it as a setting (for me the default should stay "translucent" as it make sure the notification icons are always clearly visible even if the user has a very light wallpaper).

I will have a look and keep you updated.

**Comment by xi7** [comment]
more elegant for those who use infinite screen (borderless) nowadays full translucent / transparent

**Comment by falzonv** [comment]
Hello,

Good news, it works!
The transparent status/notification bar setting will be implemented in the future release v1.3.0.

For now, I am still waiting for release v1.2.0 to be published on F-Droid because I have something to check with F-Droid screenshots before launching release v1.3.0 (issue #7 gives a link with additional details if you want).

Best regards.

**Comment by falzonv** [comment]
Hello,

This new setting has been added in release v1.3.0 which has been pushed to GitHub few minutes ago.
Please note that **it usually takes 4 to 5 days to be fully replicated in the F-Droid repository** (automatic process).

Best regards.

**Comment by falzonv** [comment]
Hello,

This was quite long (7 days!) but since today release v2.1.0 is finally available on F-Droid (for some reasons v1.3.0, v1.3.1 and v2.0.0 were "skipped" by F-Droid, or maybe their build server itself had issues...).

Since this feature is now implemented (see in the Settings), I will close this ticket but feel free to add comments if you want.

Best regards.
