### ISSUE TITLE
Support notch, especially in immersive mode

### ISSUE THREAD

**Issue by falzonv** [falzonv/discreet-launcher#50]
This ticket is created following feedback from @drewski-00h and @AeOeAa in ticket #36.
Here is the history of conversation below for continuity.

**drewski-00h**

> I'm really digging the Immersive Mode added! Is there a way to work around a phone with notch?
> <img width="50%" src="https://user-images.githubusercontent.com/83047636/118342223-0d17ad80-b4e8-11eb-830a-b3f505fbb605.jpg"/>
>
> Or does that have something to do with the wallpaper?
>
> Thanks!

**AeOeAa**

> On my phone, the wallpaper is shown "under" the notch, the default in phone settings. However, in immersed mode, there is a black bar on top.
> - this is what it looks like not immersed: <br/><img width="50%" src="https://user-images.githubusercontent.com/13118178/118354511-adfb7c80-b56b-11eb-8af0-e9000705f7c1.jpg"/>
>
> - this is what it looks like immersed: <br/><img width="50%" src="https://user-images.githubusercontent.com/13118178/118354560-e8651980-b56b-11eb-8e94-d76dfb0895ea.jpg"/>
>
> The notch setting in phone settings:
> <img width="50%" src="https://user-images.githubusercontent.com/13118178/118354689-9cff3b00-b56c-11eb-89c7-cf983b6fd254.jpg"/>

---

Hello,

Thank you very much for your feedback!
Since I never had a phone with the notch this case was completely missed to be honest...
It can probably be improved to support notch better, I will have a look and keep you updated.

@AeOeAa: I am also a bit surprised that the navigation bar is translucent on your first screenshot, normally it should be fully transparent even with immersive mode disabled... Which Android version are you using?

Best regards.

---

> **AeOeAa:** I'm at 10. Some Huawei UI.

Ok thank you I will have a look to this also (it may be something specific to Android 10 or 10+).

**Comment by falzonv** [comment]
Good news for the translucent navigation bar, there was indeed something to add starting with Android 10.
It will be fully transparent in future release v3.6.0 :-)

**Comment by AeOeAa** [comment]
Yay 👏 😀

**Comment by falzonv** [comment]
Second good news, I was able to make tests with a notch and it will be supported in future release v3.6.0 :-)
@drewski-00h, it means that on your picture the wallpaper will now be displayed around the notch instead of a black bar.

There is only one small glitch with the notch in immersive mode: when opening the favorites panel or the applications drawer, the spaces on left and right of the notch stay fully transparent instead of becoming translucent like the panel/drawer itself.

I would have preferred to have it match with the panel/drawer but apparently I cannot change that part of the interface so we will have to live with it...
Well, it will still look better than when ignoring the notch and maybe ticket #49 will provide a nice additional workaround.

**Comment by drewski-00h** [comment]
Good news! Can't wait

**Comment by falzonv** [comment]
Hello,

I am pleased to inform you that new release v3.6.0 has been published!

Here are the usual availability delays for each location:
- 4 to 8 days on F-Droid
- 0 to 2 days on Google Play
- Already available as direct APK on GitHub (https://github.com/falzonv/discreet-launcher/releases)

*Remarks:
I will leave this ticket opened until the release is effectively published on F-Droid.
You can use the export/import feature to switch from one version to another.*

Best regards.

**Comment by falzonv** [comment]
Since today v3.6.0 is available on F-Droid, I will close this ticket.
