### ISSUE TITLE
Dark Theme & System Theme

### ISSUE THREAD

**Issue by JM480** [falzonv/discreet-launcher#52]
The launcher should have settings to use a dark theme or follow the system theme.

**Comment by falzonv** [comment]
Hello,

Thank you for your suggestion, I will have a look and keep you updated!

Best regards.

**Comment by falzonv** [comment]
Hello,

Thank you for your patience, I am quite busy currently with my "real" job so the rhythm of releases which probably become a bit lower than during the previous months.

Regarding dark theme, I made some preliminary tests and there should be no issues.
Normally it will be in the next release v4.1.0, but I cannot tell exactly when this release will published.

Best regards.

**Comment by xi7** [comment]
if nobody ask for white theme, why amoled theme is not default ?

**Comment by falzonv** [comment]
The default setting will be to follow system preference, and it will also be possible to force Light/Dark theme in the settings.

**Comment by xi7** [comment]
amoled theme and dark mode is same ?

**Comment by falzonv** [comment]
Hello @JM480,

I am pleased to inform you that dark theme support has been implemented in new release v4.1.0!
This release has been published a few minutes ago.

Here are the usual availability delays for each location:
- 4 to 8 days on F-Droid
- 0 to 2 days on Google Play
- Already available as direct APK on GitHub (https://github.com/falzonv/discreet-launcher/releases)

*Remarks:
I will leave this ticket opened until the release is effectively published on F-Droid.
You can use the export/import feature to switch from one version to another.*

Best regards.

---

> amoled theme and dark mode is same ?

I am using the native Day/Night Android themes so it may vary among Android versions, but on my phone (Android 8) it is more using a dark gray than a true black.

With a launcher, what is displayed most often is the user wallpaper.
The theme is used only in the settings, the launcher menu and the long click menu, so even with Light theme it is not displayed long enough to really make a difference on battery (not like a reading app or a web browser for example).

**Comment by falzonv** [comment]
Since Thursday, release v4.1.0 is available on F-Droid so I will close this ticket.
Feel free to add comments if needed or wished.
