### ISSUE TITLE
Adaptive Icons

### ISSUE THREAD

**Issue by JM480** [falzonv/discreet-launcher#53]
The launcher should have settings to customize the shape of icons.

**Comment by falzonv** [comment]
Hello,

Thank you for your suggestion, I will have a look and keep you updated!

Best regards.

**Comment by falzonv** [comment]
Hello,

After many tests unfortunately I am not able to make it work properly, this also adds a lot of complexity in the code (not good for maintenance) and consume a lot of additional resources (cpu, memory) to process the icons.
Sorry I will not implement this feature.

Best regards.
