### ISSUE TITLE
(Congrats Dev) Add more long press options

### ISSUE THREAD

**Issue by esdreesh** [falzonv/discreet-launcher#57]
Can you put more long press icons options? Like: https://github.com/KeikaiLauncher/KeikaiLauncher

**Comment by falzonv** [comment]
Hello,

Thank you for your suggestion!
Could you precise which long press options you are interested in?

Best regards.

**Comment by esdreesh** [comment]
@falzonv "View/open selected app on play store/market". Thanks

**Comment by falzonv** [comment]
Ok for me, good idea indeed :-)
I will check how this is done in Keikai Launcher, see how it could be integrated in Discreet Launcher and keep you updated.

**Comment by falzonv** [comment]
Hello,

I am pleased to inform you that this has been implemented in new release v4.0.0!
This release has been published a few minutes ago.

Here are the usual availability delays for each location:
- 4 to 8 days on F-Droid
- 0 to 2 days on Google Play
- Already available as direct APK on GitHub (https://github.com/falzonv/discreet-launcher/releases)

*Remarks:
I will leave this ticket opened until the release is effectively published on F-Droid.
You can use the export/import feature to switch from one version to another.*

Best regards.

**Comment by falzonv** [comment]
Since today release v4.0.1 is available on F-Droid so I will close this ticket.
Feel free to add comments if needed.
