### ISSUE TITLE
Allow access to application settings with a long click

### ISSUE THREAD

**Issue by falzonv** [falzonv/discreet-launcher#6]
*This ticket is created to cover the following point from ticket #3 opened by @xi7*

*"add click and hold app go to appinfo"*

---

Hello

Very good idea!
After some tests, it seems to work fine and will be implemented soon (I plan to include it in the same release than the one which will solve the issue with double icons from ticket #3).

Regarding the exact behavior, when the user will perform a long click on an application icon, a small dialog will appear and ask if (s)he wants to open the application or its system settings.

Best regards.

**Comment by xi7** [comment]
https://user-images.githubusercontent.com/67331785/111195859-75efb180-859b-11eb-8d0e-465d3af21324.mp4

you can use side interface, just add box with manage favorite, appinfo, run. 

what u think ?

**Comment by falzonv** [comment]
Hello,

The long click on an application to access its system settings has been implemented in release v1.2.0 which has been pushed to GitHub few minutes ago.
I can confirm it is a really convenient new feature, thank you again for the suggestion and I hope you will like it!

Please note that it will probably take 4 to 5 days to be fully replicated in the applications repository.

Regarding the side interfaces, even if it looks good, I must say that I prefer the current vertical design of my application and I do not plan to integrate both directions (vertical / horizontal) for now.

Best regards.

**Comment by xi7** [comment]
working ! very useful appinfo skills

**Comment by falzonv** [comment]
Perfect, thank you for the confirmation!
