### ISSUE TITLE
Press back not closing folders on Android 5

### ISSUE THREAD

**Issue by falzonv** [falzonv/discreet-launcher#60]
This ticket is created following the bug report from @xi7 in ticket #59:

> and add press back bottom close folder. (physical, virtual, awipe) the click out folder is strange

---

It seems to be again a bug specific to Android 5, because press back works normally with other Android versions...
Thank you for the bug report, I will have a look and try to solve this also for Android 5.

**Comment by falzonv** [comment]
Hello,

I am pleased to inform you that this has been solved in new release v4.0.0!
This release has been published a few minutes ago.

Here are the usual availability delays for each location:
- 4 to 8 days on F-Droid
- 0 to 2 days on Google Play
- Already available as direct APK on GitHub (https://github.com/falzonv/discreet-launcher/releases)

*Remarks:
I will leave this ticket opened until the release is effectively published on F-Droid.
You can use the export/import feature to switch from one version to another.*

Best regards.

**Comment by xi7** [comment]
v4.0 perfect !

**Comment by falzonv** [comment]
Great, thank you for the confirmation :-)

**Comment by falzonv** [comment]
Since today release v4.0.1 is available on F-Droid so I will close this ticket.
Feel free to add comments if needed.
