### ISSUE TITLE
Taps as an alternative to swipes (accessibility option)

### ISSUE THREAD

**Issue by falzonv** [falzonv/discreet-launcher#62]
This ticket is created following a suggestion received by mail:

> Suggestion (if it's not a heavy project):  Provide an alternative tap option on the home screen for loading the favorites and drawer that can be used in place of swiping up / down.  There are phone users that still struggle with this and really miss the tap targets in Android Oreo.  For some older users the swipes are an accessibility problem.

---

Regarding the tap option, yes it should be possible!

My understanding for this is:
- If the user taps in the upper area of the home screen, it opens the favorites panel (= current "swipe down").
- If the user taps in the lower area of the home screen, it closes the favorites panel, or it opens the applications drawer if the favorites were already closed (= current "swipe up").
- To come back from the applications drawer to the home screen, the "Back" button will have to be used (as taps are already used to launch the applications).

Is it what you mean?

**Comment by falzonv** [comment]
> The tap option - yes - with a target for each in the upper and lower areas.  That would be an option in the settings to substitute for the swipe as I am guessing users that are fine with swiping won't want want to see the tap target.

For the tap targets option, I didn't understood at first that it was with actual targets, thank you for the clarification.
I will check how to do this and keep you updated.
There should be no issue, if this is not in the next release, it will probably be in the one right after ;-)

**Comment by drewski-00h** [comment]
This is really dope, I'd like to try this!

**Comment by falzonv** [comment]
Hello,

I am pleased to inform you that this has been implemented in new release v4.1.0!
This release has been published a few minutes ago.

Here are the usual availability delays for each location:
- 4 to 8 days on F-Droid
- 0 to 2 days on Google Play
- Already available as direct APK on GitHub (https://github.com/falzonv/discreet-launcher/releases)

*Remarks:
I will leave this ticket opened until the release is effectively published on F-Droid.
You can use the export/import feature to switch from one version to another.*

Best regards.

**Comment by falzonv** [comment]
Since Thursday, release v4.1.0 is available on F-Droid so I will close this ticket.
Feel free to add comments if needed or wished.
