### ISSUE TITLE
User-defined color for folder icons

### ISSUE THREAD

**Issue by drewski-00h** [falzonv/discreet-launcher#63]
Something that is bugging me about favorites folders, is that they look almost exactly the same.  I'm not always one to actually *read* the label, just look at the icon.  Is there some way to design them to be more distinguishable? Maybe add user-defined color to them?

**Comment by falzonv** [comment]
Hello,

Yes, there were already some discussions about this (ticket #35 for info) but no satisfying solution at the time (the user-defined color idea was also mentioned, but I was not able to implement it at this moment).

However, since ticket #59, we now have a good color picker and I learnt how to change the color of an Android resource (to color the menu tab with rounded corners that you suggested), so maybe it will be possible now :-)

Best regards.

**Comment by falzonv** [comment]
Hello,

Just to let you know, I am progressing quite well on this feature :-)
There are still a number of bugs to solve before it can be released (ex: renaming a folder loses its color, sometimes the first color change doesn't work, etc.) but the general idea start to be there.

![2021-06-30_folder-colors](https://user-images.githubusercontent.com/4698531/124022512-2ec3ea00-d9ed-11eb-8faa-121f75bccfe0.jpg)

Best regards.

**Comment by falzonv** [comment]
Hello,

I am pleased to inform you that this has been implemented in new release v4.7.0!
This release has been published few minutes ago.

Here are the usual availability delays for each location:
- 4 to 8 days on F-Droid
- 0 to 2 days on Google Play
- Already available as direct APK on GitHub (https://github.com/falzonv/discreet-launcher/releases)

*Remarks:
I will leave this ticket opened until the release is effectively published on F-Droid.
You can use the export/import feature to switch from one version to another.*

Best regards.

**Comment by falzonv** [comment]
Since v4.7.0 is available on F-Droid, I will close this ticket.
Feel free to add comments if needed or wished.

**Comment by DougGGlaass** [comment]
Serait-il possible d'avoir des icônes en place des trucs de maison .... J'aimerais bien avoir par exemple le ⚙️ agrandi pour indiquer le fichier

Otherwise ça dépasse tous les autres lanceurs

**Comment by falzonv** [comment]
Bonjour,

Merci, c'est gentil :-)

Je ne pense pas proposer d'autres choix d'icônes désolé, déjà parce qu'il faudrait les créer (au format SVG comme l'icône actuelle : https://github.com/falzonv/discreet-launcher/blob/main/app/src/main/res/drawable/icon_folder.xml) et je ne suis pas très bon à cela, mais surtout parce que, bien que cela semble simple de l'extérieur, ça rajouterait en fait beaucoup de complexité interne...

Cordialement.
