### ISSUE TITLE
Crash opening menu if the launcher icon is in a folder

### ISSUE THREAD

**Issue by falzonv** [falzonv/discreet-launcher#64]
This ticket is opened following bug report from @xi7 in ticket #59:

> v4.0 no work android 5 the launcher icon crash
(+ video)

---

Thank you for the bug report!

After further investigation it crashes only when the launcher icon is clicked from inside a folder (when it is directly in the applications drawer or favorites panel, not in a folder, it seems to work normally).
I have created this ticket for follow-up.

**Comment by xi7** [comment]
yes, but the last idea look better (house icon settings, house icon search....)

**Comment by falzonv** [comment]
For the crash bug, I have published a new version v4.0.1 which should solve it (different way of creating the menu).
In fact it was happening for all Android versions before 8, thank you for the bug report.

I will do the house icon search (by the way, I plan to add it in v4.1.0) but for the house icon settings I am not sure:
Someone (maybe not you, I don't remember) said in the past that the launcher icon was not really useful because we are already in the launcher and it just bring back to home screen. Now it provides menu access and becomes a bit more useful.

**Comment by xi7** [comment]
https://user-images.githubusercontent.com/67331785/120921105-78444200-c698-11eb-802b-35da0c5c0788.mp4

another bug when not have market installed

**Comment by xi7** [comment]
> 
> I will do the house icon search (by the way, I plan to add it in v4.1.0) but for the house icon settings I am not sure:
> Someone (maybe not you, I don't remember) said in the past that the launcher icon was not really useful because we are already in the launcher and it just bring back to home screen. Now it provides menu access and becomes a bit more useful.

solve it like this:

-launcher icon = set default launcher
-house icon = settings menu.

**Comment by falzonv** [comment]
Hello,

Thank you for the bug report about the market!
I didn't know this case was possible.
New ticket #68 is created for follow-up, it should be corrected in the next release.

---

Settings related to the default launcher are managed by Android, this is not something that my application should try to override or shortcut (also the Android settings for this are quite different between versions).

In the next release, the search icon will be introduced in addition to the launcher icon (search icon will be shown first in the drawer list, after the user can add it to favorites if (s)he wants). That will be two icons already for the launcher, I don't want to add a third one just for the settings if they can be accessed via the launcher icon like it is now.

Another reason to keep the launcher icon is that it may be included in icon packs someday (I know Arcticons already includes it), so for users having these packs it will be more integrated with the other applications.

Best regards.

**Comment by falzonv** [comment]
Since today release v4.0.1 is available on F-Droid so I will close this ticket.
Feel free to add comments if needed.
