### ISSUE TITLE
Permanently visible favorites panel (option)

### ISSUE THREAD

**Issue by tuch96** [falzonv/discreet-launcher#70]
Hey Vincent,
I noticed another point / proposal during my daily use. For use in the car, a permanent visibility of the favorite panel would be good. Could you incluced a function in the settings which this can be activated?

Kind regards!

**Comment by falzonv** [comment]
Hello,

Thank you for the suggestion!
Yes this should be possible, I will look how to do this and keep you updated :-)

Best regards.

**Comment by falzonv** [comment]
Hello,

Just a quick note to mention that this option will be part of the next release v4.6.0.

Best regards.

**Comment by falzonv** [comment]
Hello @tuch96,

I am pleased to inform you that this new setting has been implemented in new release v4.6.0!
This release has been published a few minutes ago.

Here are the usual availability delays for each location:
- 4 to 8 days on F-Droid
- 0 to 2 days on Google Play
- Already available as direct APK on GitHub (https://github.com/falzonv/discreet-launcher/releases)

*Remarks:
I will leave this ticket opened until the release is effectively published on F-Droid.
You can use the export/import feature to switch from one version to another.*

Best regards.

**Comment by tuch96** [comment]
Hey Vincent,

I installed the current version via f-droid and it works fine.

Many thanks for the implementation!

**Comment by falzonv** [comment]
Great, thank you for the confirmation!

I will close this ticket since v4.6.1 is now available on F-Droid (v4.6.0 was skipped).
