### ISSUE TITLE
New setting to display the current time on the home screen

### ISSUE THREAD

**Issue by mateimm** [falzonv/discreet-launcher#8]
It would be nice to have at least a clock wisget on the home screen. And maybe option to pick another that user wants.

**Comment by falzonv** [comment]
Hello,

Thank you for having tested the application and for your suggestion!

For now, I do not plan to implement widgets support. The main reasons are that it requires additional permissions and that the general idea of this launcher is to have a clutter-free home screen showing only the wallpaper.

However, we could stick a "clock text" on top of the home screen like in the two screenshots below (it would be disabled by default but there would be an option in "Settings" to show/display the clock).

What do you think about it?

**1/ With favorites panel closed**
![2021-03-19_text_clock1](https://user-images.githubusercontent.com/4698531/111816062-ac4f6880-88dc-11eb-99df-3cd6b10b5eb7.jpg)

**2/ With favorites panel opened** (the clock would move along with the panel)
![2021-03-19_text_clock2](https://user-images.githubusercontent.com/4698531/111816079-b1141c80-88dc-11eb-96aa-1a8c38cd45df.jpg)

Best regards.

**Comment by mateimm** [comment]
Hello,

Thank you for your reply.
I think that would be a good idea.
So, from settings, to be able to show or hide the clock.

Thanks,
Matei

**Comment by falzonv** [comment]
Hello,

This new setting has been added in release v1.3.0 which has been pushed to GitHub few minutes ago.
Please note that **it usually takes 4 to 5 days to be fully replicated in the F-Droid repository** (automatic process).

Best regards.

**Comment by mateimm** [comment]
Hello,
Thanks for your update.

**Comment by falzonv** [comment]
Hello,

This was quite long (7 days!) but since today release v2.1.0 is finally available on F-Droid (for some reasons v1.3.0, v1.3.1 and v2.0.0 were "skipped" by F-Droid, or maybe their build server itself had issues...).

Since this feature is now implemented, I will close this ticket but feel free to add comments if you want.

Best regards.
