### ISSUE TITLE
Add analog clock option for the home screen

### ISSUE THREAD

**Issue by falzonv** [falzonv/discreet-launcher#84]
This ticket is created following a suggestion received by mail (translated from French).

> Would it be possible to offer an analog clock? Simple, round with needles, like the "basic" one in the Lineage widget?

---

Perhaps, I have to look how it could integrates in the current code.
Added to the list ;-)

**Comment by xi7** [comment]
why not add the widget, any phone have both digital and analogic

**Comment by falzonv** [comment]
Because widget support would add a lot of complexity in the code/maintenance and requires additional permissions, this is not something that I plan to implement.

**Comment by drewski-00h** [comment]
Would it be possible to tap the clock, whether digital/analog, and have it open an app?
