### ISSUE TITLE
Add new string for favorites title field

### ISSUE THREAD

**Issue by comradekingu** [falzonv/discreet-launcher#85]
It is somewhat non-intuitive that the same "Favorites" string is used for getting to favorites, and the title field in there.
Should be more obvious that clicking it actually does anything.

I think " manage favorites" in the title field of the notification or some-such would help.

<string name="notification_title">Favorites</string>
Currently:
<string name="notification_title">Access to favorites</string>

**Comment by falzonv** [comment]
This has been added in v4.4.0 and I also updated our PR #78 accordingly.

**Comment by falzonv** [comment]
Since yesterday v4.4.0 is available on F-Droid so I will close this ticket.
