### ISSUE TITLE
Problems with import (clock, display not refreshed)

### ISSUE THREAD

**Issue by falzonv** [falzonv/discreet-launcher#86]
This ticket is created following @xi7 bug report in ticket #71:

> clock settings from an import file are not loaded and some bug if not kill app.

https://user-images.githubusercontent.com/67331785/124647558-7e326c00-de6c-11eb-815d-1b4bc86eb7a0.mp4

---

Normally it should be solved in v4.4.0 which was pushed to GitHub few minutes ago (expect 4-8 days for replication on F-Droid).

**Comment by xi7** [comment]
![Screenshot_2021-07-09-19-30-11](https://user-images.githubusercontent.com/67331785/125142253-ada3db80-e0ed-11eb-82b1-0d1da6f6c364.png)
solved but v.4.4.0 working very slow my phone, and have search into search , check the print, it make the launcher crazy after touch here

**Comment by falzonv** [comment]
Oh that is strange :-/
Sorry, I will not have the time to look into this new bug before Monday...

**Comment by xi7** [comment]
u dont need a search inside a folder if folder can use the local areal text search bar

**Comment by xi7** [comment]
supreme english, maybe u understand what i mean hoho

**Comment by falzonv** [comment]
Hello,

The main change with the search was mostly internal (in Android terms, it was changed from a "PopupWindow" to an "Activity"), the fact that it can be added to a folder is only a side effect of this change.
Maybe it was not a good idea if this change is the reason for the slowness you observe.

I have created a special APK of v4.4.0 reverting only this internal change (= v4.4.0 with the Search of v4.3.0).
https://file.re/2021/07/12/discreet-launcherv440search-v430/

=> Could you please have a look and tell me if this solves the slowness issue?
*(note: you may need to uninstall the current v4.4.0 before being able to install this one)*

If it solves the issue, I will revert the change in next release v4.5.0.

Best regards.

**Comment by xi7** [comment]
yes working fast, but back the problem need kill app after import file

**Comment by falzonv** [comment]
Ok, thank you for your feedback!
Maybe the reverted part was a bit too large...

Now, this APK should have both the search from v4.3.0 and the import bug solved of v4.4.0:
https://file.re/2021/07/12/discreet-launcher440search430try2/

**Comment by xi7** [comment]
![Screenshot_2021-07-12-16-28-49](https://user-images.githubusercontent.com/67331785/125345120-838d2c00-e32e-11eb-9a24-3fc2e714635a.png)



working perfect now, just one strange name, favorites bar name

**Comment by falzonv** [comment]
Ok great, thank you very much for your help with the tests!
I will now restart from this APK to build next release v4.5.0.

It is very strange for the favorites bar name because it changed from v4.3.0 to v4.4.0 but not in the tests APK above.
Normally the title should be "🔧 Manage favorites", I am not even sure how there could be a symbol at the end...
=> Did you also had this in the standard v4.4.0?

It might be due to encoding differences between Android phones, because I see the correct emoji on my Android 5 emulator.
Here I reused the last working APK with a different way to include the "🔧" emoji, if you want to try:
https://file.re/2021/07/12/discreet-launcher440search430emoji/
=> If it also display strange things, I will drop the emoji and stay with text only as of v4.5.0.

**Comment by xi7** [comment]
100% !!

**Comment by falzonv** [comment]
Awesome !!!
Thank you again, I will prepare and publish v4.5.0 tonight to officially fix this :-)

**Comment by falzonv** [comment]
Since yesterday v4.5.0 is available on F-Droid so I will close this ticket.
