### ISSUE TITLE
(Suggestion) Custom Fonts

### ISSUE THREAD

**Issue by Daniel-Brum** [falzonv/discreet-launcher#88]
If it's not too troublesome to implement, would it be possible to add an option to use custom fonts from .ttf/.otf files? I think this launcher could pair well with wallpapers made on KLWP (for more customized experiences) and being able to toggle the text fonts (in addition to changing the icons) would be really interesting.

Thanks in advance,
Daniel Brum

**Comment by falzonv** [comment]
Hello Daniel,

Thank you for the suggestion!
I had a look but indeed it adds a lot of complexity to several places where I prefer the launcher to stay simple and fast :-/
Sorry, custom fonts will not be implemented.

Best regards.

**Comment by Daniel-Brum** [comment]
Alright! Thanks for replying!
