### ISSUE TITLE
Once put into a folder, an app should disappear from the main list

### ISSUE THREAD

**Issue by parabolapersuader** [falzonv/discreet-launcher#92]
Once put into a folder, an app should not be shown into the main list.

Now, if the app would be put into a second folder, that won't remove it from the previous folder, only not show in the long list. Or have a virtual folder called ”All apps' if someone needs the whole list.

**Comment by falzonv** [comment]
Hello,

This is already the case.
For technical reasons, apps can be in only one place at a time in the drawer (either in a folder, or in the main list).

=> If it doesn't work for you, maybe it is a bug.
Could you provide a bit more details?
*(is it only with specific apps? any app? etc.)*

> Or have a virtual folder called ”All apps' if someone needs the whole list.

The search app already acts as a virtual "All apps" folder, it shows apps from the main list + apps in all folders.

Best regards.

**Comment by falzonv** [comment]
I will close this ticket, but feel free to add comments if needed or wished.
